buddy-ya/be

- src/main/resources/application-dev.properties
[배포 환경 DB 설정 수정](https://github.com/buddy-ya/be/issues/10)
<br><br>
배포 환경의 데이터베이스 설정을 수정
<br><br>
<br><br>
<br><br>
> fix: test 배포 서버 DB 설정 정보 수정

- src/main/java/com/team/buddyya/feed/controller/FeedController.java
- src/main/java/com/team/buddyya/feed/dto/request/feed/FeedCreateRequest.java
- src/main/java/com/team/buddyya/feed/service/FeedService.java
- src/main/resources/application.properties
[fix: 프론트 feed 전송 시 오류 수정[#32 ]](https://github.com/buddy-ya/be/issues/32)
<br><br>
프론트 feed 전송 부분에서 게시글과 이미지 같이 보낼 때 안되는 오류 수정
<br><br>
<br><br>
<br><br>
> fix: Feed 부분 Formdata 문제 해결

- src/main/java/com/team/buddyya/certification/controller/CertificationController.java
- src/main/java/com/team/buddyya/certification/service/CertificationService.java
- src/main/java/com/team/buddyya/student/controller/MyPageController.java
- src/main/java/com/team/buddyya/student/service/StudentService.java
[회원 탈퇴 및 학생 인증 초기화 #52](https://github.com/buddy-ya/be/issues/52)
<br><br>
- 학생 탈퇴
- 학생 인증 초기화
<br><br>
- 테스터를 위한 API를 위해 가장 작은 비용의 코드로 작동하는가?
- 사이드 이펙트가 있진 않을까?
<br><br>
<br><br>
> feat: 학생 탈퇴하기, 학생 인증 초기화

- src/main/java/com/team/buddyya/certification/service/CertificationService.java
pull한 내용 반영 안 된 상태로 merge되어 다시 올립니다!
<br><br>
<br><br>
<br><br>
<br><br>
> refactor: 논의한 문제 리팩토링

- src/main/java/com/team/buddyya/chatting/domain/Chat.java
- src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
- src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
- src/main/java/com/team/buddyya/chatting/repository/ChatRepository.java
- src/main/java/com/team/buddyya/chatting/repository/ChatroomRepository.java
- src/main/java/com/team/buddyya/chatting/repository/ChatroomStudentRepository.java
[실시간 채팅 구현을 위한 초기 설정[#57 ]](https://github.com/buddy-ya/be/issues/57)
<br><br>
- 채팅방 관련 도메인 생성
- 채팅방 Repository 생성
<br><br>
<br><br>
https://github.com/buddy-ya/be/pull/58/files/cde56c3cbc419990d6d83d0d3ba70d042008ff67
<br><br>
> feat: 채팅 구현 초기 설정

- src/main/java/com/team/buddyya/auth/jwt/JwtUtils.java
- src/main/java/com/team/buddyya/common/config/SecurityConfig.java
[프론트 연동 오류 수정[#74 ]](https://github.com/buddy-ya/be/issues/74)
<br><br>
- spring security 설정 수정
- jwt 토큰 파싱 key 값 수정
<br><br>
<br><br>
<br><br>
> fix: spring security 경로 수정과 jwt 토큰 파싱 수정 (#74)

- src/main/java/com/team/buddyya/student/controller/UserController.java
- src/main/java/com/team/buddyya/student/dto/response/UserProfileResponse.java
- src/main/java/com/team/buddyya/student/service/MyPageService.java
[UserProfileResponse에 userId 추가 & 회원 정보 조회 api 통합 & 회원 탈퇴 엔드 포인트 수정](https://github.com/buddy-ya/be/issues/78)[#78]
<br><br>
- UserProfileResponse에 userId 추가
- 회원 정보 조회 api 통합
- 회원 탈퇴 엔드 포인트 수정
<br><br>
<br><br>
<br><br>
> refactor:UserProfileResponse에 userId 추가 & 회원 정보 조회 api 통합 & 회원 탈퇴 엔드 포인트 수정

- src/main/java/com/team/buddyya/notification/domain/RequestNotification.java
- src/main/java/com/team/buddyya/notification/service/NotificationService.java
[알림 전송 기능에서 json 직렬화 문제 해결](https://github.com/buddy-ya/be/issues/104)[#104]
<br><br>
- RequestNotification 클래스에 Getter 메서드 추가
<br><br>
<br><br>
<br><br>
> 알림 전송 기능에서 json 직렬화 문제 RequestNotification에 @Getter 추가해서 해결 

- src/main/java/com/team/buddyya/auth/controller/AuthController.java
- src/main/java/com/team/buddyya/common/config/SecurityConfig.java
[https 적용 테스트[#102 ]](urhttps://github.com/buddy-ya/be/issues/102)
<br><br>
https 테스트를 위한 api 추가
<br><br>
<br><br>
<br><br>
> feat: https test를 위한 dummy api(#102)

- src/main/resources/application.properties
<br><br>
- 테스트를 위한 jwt 토큰 시간 수정
<br><br>
<br><br>
<br><br>
> chore: jwt 토큰 시간 수정

- src/main/java/com/team/buddyya/auth/service/AuthService.java
<br><br>
jwt 토큰 claim 값 수정
<br><br>
<br><br>
<br><br>
> chore: jwt 토큰 클레임 수정

- src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
- src/main/resources/application.properties
<br><br>
- 리프레시 토큰 재발급 받지 않도록 수정
<br><br>
<br><br>
<br><br>
> fix: 리프레시 토큰 재발급 받지 않도록 수정

- src/main/java/com/team/buddyya/auth/service/AuthService.java
[https://github.com/buddy-ya/be/issues/102 [#102 ]](https://github.com/buddy-ya/be/pull/110)
<br><br>
- 리프레시 토큰 재발급 받지 않도록 수정
<br><br>
<br><br>
<br><br>
> refactor: 정책에 따라 refresh 토큰 재발급 받지 않도록 수정

- src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
- src/main/java/com/team/buddyya/common/domain/BaseTime.java
- src/main/java/com/team/buddyya/common/domain/CreatedTime.java
[create_date -> created_date 수정 [#114] ](https://github.com/buddy-ya/be/issues/114)
<br><br>
- create_date -> created_date 수정
<br><br>
<br><br>
<br><br>
> refactor: create_date -> created_date로 수정

- build.gradle
- src/main/resources/db/migration/V1__init.sql
[출시를 위한 Flyway(마이그레이션툴) 적용](https://github.com/buddy-ya/be/issues/118)[#118]
<br><br>
- Flyway 관련 의존성 및 설정 추가
- ddl-auto validate로 변경
- db 스크립트 작성
<br><br>
```
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.fail-on-missing-locations=true
```
- **`spring.flyway.enabled=true`**
→ Flyway를 활성화하여 애플리케이션 시작 시 자동으로 마이그레이션 실행.
- **`spring.flyway.baseline-on-migrate=false`**
→ 기존 데이터베이스를 baseline으로 간주하지 않고, V1부터 마이그레이션을 순차적으로 실행.
- **`spring.flyway.locations=classpath:db/migration`**
→ 마이그레이션 SQL 파일을 `src/main/resources/db/migration`에서 찾도록 설정.
- **`spring.flyway.validate-on-migrate=true`**
→ 실행 전에 기존 마이그레이션과 현재 상태를 비교하여 일관성을 검증하고 충돌이 있으면 오류 발생.
- …
> chore: 출시를 위한 Flyway(마이그레이션툴) 적용

- src/main/java/com/team/buddyya/admin/domain/Admin.java
- src/main/java/com/team/buddyya/admin/dto/request/StudentVerificationRequest.java
- src/main/java/com/team/buddyya/admin/service/AdminService.java
- src/main/java/com/team/buddyya/auth/domain/AuthToken.java
- src/main/java/com/team/buddyya/certification/domain/StudentEmail.java
- src/main/java/com/team/buddyya/certification/domain/StudentIdCard.java
- src/main/java/com/team/buddyya/chatting/domain/Chat.java
- src/main/java/com/team/buddyya/chatting/domain/ChatRequest.java
- src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
- src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
- src/main/java/com/team/buddyya/common/DataLoader.java
- src/main/java/com/team/buddyya/common/domain/BaseTime.java
- src/main/java/com/team/buddyya/common/domain/CreatedTime.java
- src/main/java/com/team/buddyya/notification/domain/ExpoToken.java
- src/main/java/com/team/buddyya/report/domain/Report.java
- src/main/java/com/team/buddyya/report/service/ReportService.java
- src/main/java/com/team/buddyya/student/domain/Avatar.java
- src/main/java/com/team/buddyya/student/domain/Buddy.java
- src/main/java/com/team/buddyya/student/domain/Interest.java
- src/main/java/com/team/buddyya/student/domain/Language.java
- src/main/java/com/team/buddyya/student/domain/Major.java
- src/main/java/com/team/buddyya/student/domain/Role.java
- src/main/java/com/team/buddyya/student/domain/Student.java
- src/main/java/com/team/buddyya/student/domain/University.java
- src/main/java/com/team/buddyya/student/repository/StudentRepository.java
- src/main/java/com/team/buddyya/student/service/StudentService.java
- src/main/resources/db/migration/V1__init.sql
[도메인 제약 조건 수정 [#119] ](https://github.com/buddy-ya/be/issues/119)
<br><br>
- flyway로 마이그레이션을 적용하기 위해서는 테이블 생성문을 직접 작성해야 합니다
- 테이블 생성문을 작성하기 위해 설계한 도메인들의 제약 조건(null, unique)과 DB engine에 대해 조사
- null이 필요하지 않은 모든 부분에 대해서 `nullable = false` 적용
- email 같은 유일한 값에 대해서 unique 속성 적용
https://mark12345.notion.site/DB-19917d6854eb80938b6bc7eb4db3f542?pvs=4
<br><br>
<br><br>
https://github.com/buddy-ya/be/pull/120/files/f178531d53fdd067be11ce8e07ec01c359985a65
<br><br>
> refactor: 도메인 제약 조건 수정

- src/main/java/com/team/buddyya/chatting/service/ChatService.java
- src/main/java/com/team/buddyya/notification/service/NotificationService.java
[채팅 요청 수락 알림](https://github.com/buddy-ya/be/issues/140)[#140]
<br><br>
- 채팅 요청 수락 알림 로직 추가
<br><br>
- 코드 컨벤션에 어긋난 부분이 있나요?
<br><br>
<br><br>
> feat: 채팅 요청 수락 알림

- src/main/java/com/team/buddyya/common/config/SecurityConfig.java
- src/main/java/com/team/buddyya/student/controller/UserController.java
- src/main/java/com/team/buddyya/student/domain/University.java
- src/main/java/com/team/buddyya/student/dto/response/UniversityResponse.java
- src/main/java/com/team/buddyya/student/repository/UniversityRepository.java
- src/main/java/com/team/buddyya/student/service/StudentService.java
- src/main/java/com/team/buddyya/student/service/UniversityService.java
- src/main/resources/db/migration/V5__Add_university_active_column.sql
[대학교 조회 기능](https://github.com/buddy-ya/be/issues/159)
<br><br>
- 활동 대학교 조회 API 구현
-> 온보딩에서 대학교 목록을 보여줘야할 때 데이터베이스에 저장되어있는 대학교 중
우리가 활동중인 대학교의 리스트를 보여주는 API
- 데이터베이스에 대학교 키 수정 및 저장
<br><br>
- 현재 `UserController`에 작성하였는데 따로 `UniversityController`로 분리시키는게 맞을까?
- 코드 컨벤션에 어긋난 부분은 없는가?
<br><br>
<br><br>
> feat: 대학교 조회 기능 구현

- src/main/java/com/team/buddyya/certification/service/MessageSendService.java
- src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
[앱 심사를 위한 테스트 계정 생성 [#173]](https://github.com/buddy-ya/be/issues/173)
<br><br>
- 테스트 계정 통과를 위한 규칙 추가
<br><br>
<br><br>
<br><br>
> deploy: 배포를 위한 테스트 계정 생성

- src/main/java/com/team/buddyya/chatting/controller/ChatController.java
- src/main/java/com/team/buddyya/common/config/SecurityConfig.java
[사진 전송 문제 해결하여 security 원상 복구](https://github.com/buddy-ya/be/issues/183)[#183]
<br><br>
- ngnix가 포워딩을 잘 못하고 있는지 확인하기 위해 로그 출력
<br><br>
<br><br>
<br><br>
> refactor: 사진 전송 문제 해결하여 security 원상 복구

- src/main/java/com/team/buddyya/chatting/controller/ChatController.java
<br><br>
<br><br>
<br><br>
<br><br>
> refactor: 채팅 이미지 전송 관련 코드 제거

- src/main/java/com/team/buddyya/common/config/LoggingFilter.java
- src/main/java/com/team/buddyya/common/config/SecurityConfig.java
[로그 확인 테스트 [#189]](https://github.com/buddy-ya/be/issues)
<br><br>
- 로그 확인 테스트
<br><br>
<br><br>
<br><br>
> chore: api 요청 시 로깅 추가

- src/main/java/com/team/buddyya/certification/controller/PhoneAuthenticationController.java
- src/main/java/com/team/buddyya/certification/domain/TestAccount.java
- src/main/java/com/team/buddyya/certification/dto/request/TestAccountRequest.java
- src/main/java/com/team/buddyya/certification/dto/response/TestAccountResponse.java
- src/main/java/com/team/buddyya/certification/repository/TestAccountRepository.java
- src/main/java/com/team/buddyya/certification/service/MessageSendService.java
- src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
- src/main/resources/db/migration/V7__create_test_account_table.sql
[테스트 계정 목록 DB 생성 [#179]](https://github.com/buddy-ya/be/issues/179)
<br><br>
- 기존에 전화번호 prefix를 통해 테스트 계정인지 확인 -> 관리자가 등록한 테스트 계정인지 확인
- 관리자가 등록한 테스트 계정은 인증 코드가 발송되지 않음
<br><br>
<br><br>
<br><br>
> feat: 테스트 계정 목록 DB 생성

- src/main/java/com/team/buddyya/student/service/StudentService.java
<br><br>
<br><br>
<br><br>
<br><br>
> fix: 자기 정보 조회 시 파라미터, 토큰에서 받은 userId 비교 로그 추가 (#193)

- src/main/java/com/team/buddyya/student/service/StudentService.java
<br><br>
<br><br>
<br><br>
<br><br>
> fix: == 연산이 문제 인것 같아 equals로 수정 (#193)

- src/main/java/com/team/buddyya/notification/domain/ExpoToken.java
[ExpoToken의 token값을 null값 허용으로 변경](https://github.com/buddy-ya/be/issues/201)[#201]
<br><br>
<br><br>
<br><br>
<br><br>
> refactor: ExpoToken의 토큰 nullable 허용

- src/main/java/com/team/buddyya/student/dto/response/UniversityResponse.java
[대학교 조회 응답 구조 변경](https://github.com/buddy-ya/be/issues/162)[#162]
<br><br>
`현재 응답 구조`
```
[
{
"university": "sejong"
},
{
"university": "konkuk"
}
]
```
`id(universityId)를 추가한 구조`
```
[
{
"id"  : 1,
"university": "sejong"
},
{
"id"  : 2,
"university": "konkuk"
}
]
```
<br><br>
<br><br>
<br><br>
> refactor: 활동 대학교 조회 응답 DTO에 대학교 아이디 추가

- src/main/java/com/team/buddyya/match/dto/response/MatchResponse.java
- src/main/java/com/team/buddyya/match/dto/response/MatchStatusResponse.java
[매칭 성공 시 응답값 추가 및 chatRoodId 오타 수정](https://github.com/buddy-ya/be/issues/211)[#211 ]
<br><br>
- 매칭 성공시 응답 값 추가
- 매칭 응답 chatRoodId 오타 수정 -> chatRoomId
<br><br>
<br><br>
<br><br>
> 매칭 성공 시 응답값 추가 및 chatRoodId 오타 수정

- src/main/java/com/team/buddyya/point/repository/PointStatusRepository.java
- src/main/java/com/team/buddyya/point/service/PointService.java
[포인트 기록 조회 시간순으로 변경](https://github.com/buddy-ya/be/issues/217)[#217]
<br><br>
- 포인트 기록 조회 시간순으로 변경
<br><br>
<br><br>
<br><br>
> refactor: 포인트 기록을 최신순으로 반환

- src/main/java/com/team/buddyya/certification/domain/PhoneInfo.java
- src/main/java/com/team/buddyya/certification/service/MessageSendService.java
<br><br>
<br><br>
<br><br>
<br><br>
> refactor: udId는 nullable하게 받도록 변경

- src/main/java/com/team/buddyya/certification/domain/PhoneInfo.java
- src/main/java/com/team/buddyya/certification/service/MessageSendService.java
- src/main/resources/db/migration/V14__Update_ud_id_to_udid.sql
<br><br>
<br><br>
<br><br>
<br><br>
> udId는 nullable하게 받도록 변경 

- src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
- src/main/java/com/team/buddyya/student/service/StudentService.java
[userResponse에 읽지 않은 총 메시지 추가 [#227]](https://github.com/buddy-ya/be/issues/227)
<br><br>
- 마이페이지 조회 시  UserResponse에 totalUnreadCount 필드 추가
<br><br>
- 컨벤션이 잘 지켜졌는가?
<br><br>
<br><br>
> feat: 마이페이지 조회 시 UserResponse에 totalUnreadCount 필드 추가

- src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
- src/main/java/com/team/buddyya/student/service/InvitationService.java
[추천인 코드에 자신의 추천인 코드를 입력 할 시 혜택받지 못하도록 수정](https://github.com/buddy-ya/be/issues/246)[#246]
<br><br>
- 추천인 코드에 자신의 추천인 코드를 입력 할 시 혜택받지 못하도록 수정
<br><br>
<br><br>
<br><br>
> fix: 추천인 코드에 자신의 추천인 코드를 입력 할 시 혜택받지 못하도록 수정

- src/main/java/com/team/buddyya/match/dto/response/MatchResponse.java
- src/main/java/com/team/buddyya/match/dto/response/MatchStatusResponse.java
- src/main/java/com/team/buddyya/match/exception/MatchExceptionType.java
- src/main/java/com/team/buddyya/match/service/BasicMatchService.java
- src/main/java/com/team/buddyya/student/domain/MatchingProfile.java
[매칭 시 매칭 프로필 없으면 예외 추가 [#255]](https://github.com/buddy-ya/be/issues)
<br><br>
- 매칭 프로필 작성되지 않은 상태에서 매칭 보내졌을 때 예외 처리
<br><br>
<br><br>
<br><br>
> feat: 매칭 시 프로필 미완성 시 예외 처리

- src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
[테스트 계정 로그인 시 send_message_count 초기화 [#262]](https://github.com/b\uddy-ya/be/issues/262)
<br><br>
- 테스트 계정으로 로그인 성공 시 send_message_count 초기화
<br><br>
<br><br>
<br><br>
> fix: 테스트 계정으로 로그인 성공 시 send_message_count 초기화

- src/main/java/com/team/buddyya/chatting/controller/ChatRequestController.java
- src/main/java/com/team/buddyya/chatting/service/ChatRequestService.java
- src/main/java/com/team/buddyya/chatting/service/ChatService.java
[채팅 요청 관련 포인트 로직 제거](https://github.com/buddy-ya/be/issues/273)[#273]
<br><br>
- 채팅 요청 관련 포인트 로직 제거
<br><br>
<br><br>
<br><br>
> refactor: 채팅 요청 관련 포인트 로직 제거

- src/main/java/com/team/buddyya/student/domain/CharacterProfileImage.java
[s3 캐싱 문제 해결 url 변경 [#277]](https://github.com/buddy-ya/be/issues/277)
<br><br>
- 캐시 문제로 인한 image url변경
<br><br>
<br><br>
<br><br>
> fix: s3 캐시 문제로 인해 url 수정

- src/main/java/com/team/buddyya/match/service/BasicMatchService.java
<br><br>
<br><br>
<br><br>
<br><br>
> refactor: 매칭 요청의 유효성을 검증할 때 파라미터로 전달 되는 값 순서가 잘못되어 수정 

- src/main/java/com/team/buddyya/auth/jwt/CustomAccessDeniedHandler.java
- src/main/java/com/team/buddyya/auth/jwt/CustomAuthenticationEntryPoint.java
- src/main/java/com/team/buddyya/auth/jwt/JwtAuthFilter.java
- src/main/java/com/team/buddyya/auth/jwt/JwtUtils.java
- src/main/java/com/team/buddyya/auth/jwt/WebSocketAuthInterceptor.java
- src/main/java/com/team/buddyya/auth/service/AuthService.java
- src/main/java/com/team/buddyya/chatting/service/ChatHandler.java
- src/main/java/com/team/buddyya/chatting/service/ChatRequestService.java
- src/main/java/com/team/buddyya/chatting/service/ChatService.java
- src/main/java/com/team/buddyya/common/config/LoggingFilter.java
- src/main/java/com/team/buddyya/common/config/WebSocketConfig.java
- src/main/java/com/team/buddyya/common/exception/GlobalExceptionHandler.java
- src/main/java/com/team/buddyya/feed/service/FeedLikeService.java
- src/main/java/com/team/buddyya/feed/service/FeedService.java
- src/main/java/com/team/buddyya/report/repository/ReportRepository.java
- src/main/java/com/team/buddyya/student/domain/CharacterProfileImage.java
- src/main/java/com/team/buddyya/student/service/OnBoardingService.java
[출시 전 변경 사항 반영 [#281]](https://github.com/buddy-ya/be/issues/281)
<br><br>
- 이미지 9번이 아닌 5번 사용
- 신고 시 게시글 이미지 삭제되지 않도록
- 개발 환경에서 사용한 로그 정리
<br><br>
<br><br>
<br><br>
> refactor: 신고 시 게시글 이미지 삭제 x, 로그 정리

- src/main/java/com/team/buddyya/match/service/BasicMatchService.java
- src/main/java/com/team/buddyya/student/service/OnBoardingService.java
[배포 전 로그 정리 [#285]](https://github.com/buddy-ya/be/issues/285)
<br><br>
<br><br>
<br><br>
<br><br>
> refactor: match 로그 추가, 계정 생성 시 id 로그 추가

- src/main/resources/db/migration/V20__Add_match_request_chinese_available.sql
<br><br>
<br><br>
<br><br>
<br><br>
> chore: chinese_available 을 MatchRequest에 추가하는 마이그레이션 스크립트 작성 (#290)

- src/main/resources/db/migration/V20__Add_match_request_chinese_available.sql
<br><br>
<br><br>
<br><br>
<br><br>
> chore: 매칭 프로필에서 외래키 추가 조건 마이그레이션 스크립트에서 제거 (#292)

- src/main/java/com/team/buddyya/notification/domain/RequestNotification.java
- src/main/java/com/team/buddyya/notification/service/NotificationService.java
…추가 (#296)
<br><br>
<br><br>
<br><br>
<br><br>
> fix: 안드로이드에서 헤드업 알림이 가지 않아 RequestNotification의 구조에 priority high 설정

- src/main/java/com/team/buddyya/notification/domain/RequestNotification.java
- src/main/java/com/team/buddyya/notification/service/NotificationService.java
<br><br>
<br><br>
<br><br>
<br><br>
> fix: 안드로이드 헤드업 알림이 보내지지 않아 channelId를 포함해서 전송

- src/main/java/com/team/buddyya/admin/service/AdminService.java
- src/main/java/com/team/buddyya/certification/repository/StudentIdCardRepository.java
- src/main/resources/db/migration/V21__Add_matching_profile_foreign_key.sql
[관리자가 반려한 학생증 재조회 되지 않게 수정 [#300]](https://github.com/buddy-ya/be/issues/300)
<br><br>
<br><br>
<br><br>
<br><br>
> fix: 관리자 학생증 반려 시 재조회되지 않도록 수정 

- src/main/java/com/team/buddyya/student/service/StudentService.java
[출석 이벤트 포인트 지급기능 반려](https://github.com/buddy-ya/be/issues/309)[#309]
<br><br>
- 출석 이벤트 포인트 지급 기능 주석 처리
<br><br>
<br><br>
<br><br>
> refactor: getUserInfo메서드에서 출석 이벤트 참여 포인트 지급 기능 주석 처리

- src/main/java/com/team/buddyya/chatting/service/ChatService.java
[채팅요청 수락으로 채팅방 생성시 기존 채팅방 불러오는 현상 해결 #311](https://github.com/buddy-ya/be/issues/311)
<br><br>
- `createOrGetChatRoom`에서 기존 채팅방 검사 로직 제거
<br><br>
- 매칭에서의 로직이 `createOrGetChatRoom`에 의존적이진 않은지.
<br><br>
<br><br>
> Fix: 채팅요청 수락으로 채팅방 생성시 기존 채팅방 불러오는 현상 해결

- src/main/java/com/team/buddyya/mission/dto/PointMissionRewardResponse.java
- src/main/java/com/team/buddyya/mission/exception/MissionException.java
- src/main/java/com/team/buddyya/mission/exception/MissionExceptionType.java
- src/main/java/com/team/buddyya/mission/service/MissionService.java
[https://github.com/buddy-ya/be/issues/333](https://github.com/buddy-ya/be/issues/333)
<br><br>
- 출석 체크시 참여 여부와 이벤트로 받은 총 포인트를 추가로 반환
- 오늘 이미 출석 체크를 했으면 예외로 반환
<br><br>
<br><br>
<br><br>
> refactor: 출석 체크시 참여 여부와 이벤트로 받은 총 포인트를 추가로 반환

- .github/workflows/gradle.yml
[ci cd 파이프라인 작성 [#342]](https://github.com/buddy-ya/be/issues/342)
<br><br>
- ci / cd 스크립트 작성
<br><br>
<br><br>
<br><br>
> deploy: ci / cd 스크립트 작성

- src/main/java/com/team/buddyya/match/exception/MatchExceptionType.java
- src/main/java/com/team/buddyya/match/repository/MatchedHistoryRepository.java
- src/main/java/com/team/buddyya/match/service/BasicMatchService.java
[서울 선택 시 전체 대학 포함 & 하루 2회 매칭 가능하도록 변경](https://github.com/buddy-ya/be/issues/352)[#352]
<br><br>
- '서울' 선택 시 본인 대학 포함 전체 서울 지역 대학 유저들과 매칭되도록 수정
- 하루 매칭 가능 횟수 1회 → 2회로 증대
<br><br>
<br><br>
<br><br>
> refactor: 서울 선택 시 전체 대학 포함 & 하루 2회 매칭 가능하도록 변경
