src/main/java/com/team/buddyya/student/domain/Student.java
src/main/resources/application.properties

[이메일 인증 api 개발](https://github.com/buddy-ya/be/issues/1) #1
<br><br>
- MySQL 데이터베이스 초기 설정
- 공용으로 사용하기 위한 Student 기본 Entity 생성
<br><br>
<br><br>
https://github.com/buddy-ya/be/pull/5/files/f3ccb4b5d17991142bd1f7785d3fecb42424e398
<br><br>

feat: MySQL 기본 설정 Student 기본 Entity 생성

---

build.gradle
src/main/java/com/team/buddyya/auth/domain/AuthToken.java
src/main/java/com/team/buddyya/auth/domain/CustomUserDetails.java
src/main/java/com/team/buddyya/auth/domain/StudentInfo.java
src/main/java/com/team/buddyya/auth/dto/LoginStudentInfo.java
src/main/java/com/team/buddyya/auth/dto/request/TokenInfoRequest.java
src/main/java/com/team/buddyya/auth/exception/AuthException.java
src/main/java/com/team/buddyya/auth/exception/AuthExceptionType.java
src/main/java/com/team/buddyya/auth/jwt/CustomAccessDeniedHandler.java
src/main/java/com/team/buddyya/auth/jwt/CustomAuthenticationEntryPoint.java
src/main/java/com/team/buddyya/auth/jwt/JwtAuthFilter.java
src/main/java/com/team/buddyya/auth/jwt/JwtExceptionFilter.java
src/main/java/com/team/buddyya/auth/jwt/JwtUtils.java
src/main/java/com/team/buddyya/auth/repository/AuthTokenRepository.java
src/main/java/com/team/buddyya/auth/service/CustomUserDetailsService.java
src/main/java/com/team/buddyya/common/config/SecurityConfig.java
src/main/java/com/team/buddyya/student/domain/Student.java
src/main/java/com/team/buddyya/student/dto/response/OnBoardingResponse.java
src/main/java/com/team/buddyya/student/exception/OnBoardingExceptionType.java
src/main/java/com/team/buddyya/student/service/OnBoardingService.java
src/main/resources/application.properties

[Spring Security 설정[#6]](https://github.com/buddy-ya/be/issues/6)
<br><br>
- jwt를 관리하는 **JwtUtils** 추가
- accessToken 발급 기능
- refreshToken 발급 기능
- 토큰 검증 기능
- 토큰 claim 파싱 기능
- **학생 생성 후 accessToken, refreshToken 발급 로직** 수정
- **인증과 인가를 위한 Spring Security** 기능 도입
-  jwtAuthFilter로 인증된 사용자 검증
- 일반 사용자와 관리자 구분(인가 처리)
- 인증과 인가 **filter에서 발생하는 오류 직접 처리**
<br><br>
- 인증과 인가 처리가 제대로 되었는가?
Spring Security에 깊은 이해가 필요할 것 같아 설명은 PR로 부족하다고 생각합니다. 따라서 PR에는 간략하게 핵심 로직만 설명하고 대면으로 자세한 흐름에 대해서 설명 할 예정입니다!
1. **요청 수신**
- 클라이언트가 서버로 HTTP 요청을 보냅니다
2. **필터 체인**
- 요청은 `SecurityFilterChain`을 거쳐 여러 보안 필터를 통과합니다
- 이 때 csrf 비활성화, jwt 토큰 인증 방식을 사용하기 때문에 세션 방식 비활성화, 폼 기반 로그인 비활성화, http Basic 인증 비활성화 설정을 하였습니다
- `SecurityConfig` 클래스에서 필터 체인을 설정합니다
3. **JWT 인증 처리 - JwtAuthFilter**
- …

feat: 인증 및 인가 처리를 위한 Security 설정

---

src/main/java/com/team/buddyya/auth/controller/AuthController.java
src/main/java/com/team/buddyya/auth/dto/request/TokenReissueRequest.java
src/main/java/com/team/buddyya/auth/dto/response/TokenReissueResponse.java
src/main/java/com/team/buddyya/auth/exception/AuthExceptionType.java
src/main/java/com/team/buddyya/auth/service/AuthService.java
src/main/java/com/team/buddyya/common/config/SecurityConfig.java

[토큰 만료 시 재발급[#12]](https://github.com/buddy-ya/be/issues/12)
<br><br>
- 토큰 만료 시 재발급하는 api 추가
- 발급한 토큰을 보내 테스트하는 api 추가
<br><br>
- 토큰 재발급에 필요없는 부분은 없는가?
accessToken 만료 시 refreshToken을 보내 재발급하는 기능입니다
**accessToken의 기간은 1일**, **refreshToken의 기간은 2달**로 정했습니다
accessToken이 만료된 경우 헤더에 refreshToken을 포함하여 auth/reissue api를 호출하여 reissueToken 메서드를 실행합니다
DB에 저장한 refreshToken과 보낸 **refreshToken이 일치하는지 확인** 후 **accessToken을 갱신**합니다
이 때 **`refreshToken의 기간이 30일보다 적게 남았다면 refreshToken도 같이 갱신`** 합니다
refreshToken의 기간이 30일보다 많이 남았다면 accessToken만 갱신해줍니다
만약 refreshToken의 기간이 만료됐으면 프론트에서 재로그인을 수행할 수 있게 **`만료된 토큰입니다`** 오류를 보냅니다
응답 형식은 다음과 같습니다.
**`refreshToken이 30일보다 적게 남았을 때`**
```
{
"accessToken": "{accessToken}",
"refreshToken": "{refreshToken}"
}
```
**`refreshToken이 …

feat: 토큰 만료 시 재발급 기능

---

src/main/java/com/team/buddyya/feed/controller/FeedController.java
src/main/java/com/team/buddyya/feed/domain/BookMark.java
src/main/java/com/team/buddyya/feed/domain/Category.java
src/main/java/com/team/buddyya/feed/domain/Comment.java
src/main/java/com/team/buddyya/feed/domain/Feed.java
src/main/java/com/team/buddyya/feed/domain/FeedImage.java
src/main/java/com/team/buddyya/feed/domain/FeedUserAction.java
src/main/java/com/team/buddyya/feed/domain/Like.java
src/main/java/com/team/buddyya/feed/dto/request/FeedCreateRequest.java
src/main/java/com/team/buddyya/feed/dto/request/FeedListRequest.java
src/main/java/com/team/buddyya/feed/dto/request/FeedUpdateRequest.java
src/main/java/com/team/buddyya/feed/dto/response/FeedCreateResponse.java
src/main/java/com/team/buddyya/feed/dto/response/FeedListItemResponse.java
src/main/java/com/team/buddyya/feed/dto/response/FeedListResponse.java
src/main/java/com/team/buddyya/feed/dto/response/FeedResponse.java
src/main/java/com/team/buddyya/feed/exception/FeedException.java
src/main/java/com/team/buddyya/feed/exception/FeedExceptionType.java
src/main/java/com/team/buddyya/feed/respository/BookmarkRepository.java
src/main/java/com/team/buddyya/feed/respository/CategoryRepository.java
src/main/java/com/team/buddyya/feed/respository/CommentRepository.java
src/main/java/com/team/buddyya/feed/respository/FeedRepository.java
src/main/java/com/team/buddyya/feed/respository/LikeRepository.java
src/main/java/com/team/buddyya/feed/service/BookmarkService.java
src/main/java/com/team/buddyya/feed/service/CategoryService.java
src/main/java/com/team/buddyya/feed/service/FeedService.java
src/main/java/com/team/buddyya/feed/service/LikeSevice.java

[피드 기능 개발 #22](https://github.com/buddy-ya/be/issues/22)
<br><br>
- Feed 및 관련 Entity 구현 (Feed, Category, Like, Bookmark)
- 피드 목록 조회/상세 조회/생성/수정/삭제 API 구현
- 피드 조회시 Page 처리를 통한 피드 목록 페이지네이션 구현 
피드에 `댓글`, `좋아요 및 북마크`, `사진 파일`에 대한 부분은 다음 PR에 구현하겠습니다.
<br><br>
- 조회의 경우 조회를 한 곳에서 `Optional` 예외처리를 하지않고 
해당 도메인의 서비스 계층에서 `findBy-` 메서드를 제공하여 예외처리 코드의 중복 방지.
- 메서드안에서 개행을 하지못하므로 메서드가 길어졌을 때 분리하여 가독성을 높임. 
<br><br>
- 게시글이 50개만 넘어가도 프론트엔드 렌더링 성능에 영향이 있을 것으로 판단
- Spring Data JPA의 페이징 기능을 활용하여 10개씩 피드 목록 반환하도록 구현
- 저희 게시글은 조회 기준에 카테고리가 있기 때문에, `Pageable` 로 요청을 받기에는 제한이 있었습니다.
따라서 카테고리 필드가 담긴 `RequestDTO`를 만들어 요청을 처리했습니다.
- `Repositroy`에서 조회 기능을 수행하면 `Optional`객체가 반환되기 때문에, 요청한 쪽에서 반드시 예외처리를 해야합니다.
-  조회의 경우 해당 서비스 계층에서 예외처리까지 진행하고 조회된 객체를 반환하는 메서드를 제공하는건 어떨까요? …

feat: 피드 목록 조회/상세 조회/생성/수정/삭제 API 구현

---

src/main/java/com/team/buddyya/admin/controller/AdminController.java
src/main/java/com/team/buddyya/admin/dto/request/StudentVerificationRequest.java
src/main/java/com/team/buddyya/admin/dto/response/StudentIdCardListResponse.java
src/main/java/com/team/buddyya/admin/dto/response/StudentIdCardResponse.java
src/main/java/com/team/buddyya/admin/dto/response/StudentVerificationResponse.java
src/main/java/com/team/buddyya/admin/service/AdminService.java
src/main/java/com/team/buddyya/certification/domain/StudentIdCard.java
src/main/java/com/team/buddyya/certification/repository/StudentIdCardRepository.java
src/main/java/com/team/buddyya/certification/service/CertificationService.java
src/main/java/com/team/buddyya/common/config/SecurityConfig.java
src/main/java/com/team/buddyya/common/service/S3UploadService.java
src/main/java/com/team/buddyya/student/domain/Student.java
src/main/java/com/team/buddyya/student/repository/StudentRepository.java
src/main/java/com/team/buddyya/student/service/StudentService.java

[관리자는 학생증 인증 승인, 혹은 반려[#21 ]](https://github.com/buddy-ya/be/issues/21)
<br><br>
- 관리자가 학생증 사진 목록을 조회하는 기능
- 관리자가 인증을 허가하면 인증된 회원으로 변경하는 기능
<br><br>
**`학생증 조회하는 api`**
```
return studentIdCardRepository.findAllByOrderByCreatedDateAsc().stream()
.map(StudentIdCardResponse::from)
.collect(Collectors.toList());
```
다음과 같이 요청이 오래된 순으로 반환하도록 설계하였습니다
**`인증 승인, 반려 하는 api`**
```
public StudentVerificationResponse verifyStudentIdCard(StudentVerificationRequest request) {
s3UploadService.deleteFile(STUDENT_ID_CARD.getDirectoryName(), request.imageUrl());
Student student = studentRepository.findById(request.studentId())
.orElseThrow(() -> new StudentException(StudentExceptionType.STUDENT_NOT_FOUND));
studentIdCardRepository.deleteByStudent(student);
if (request.studentNumber() == null) {
return new …
```

feat: 관리자의 학생증 인증 승인, 반려하는 기능

---

src/main/java/com/team/buddyya/common/DataLoader.java
src/main/java/com/team/buddyya/feed/controller/FeedController.java
src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
src/main/java/com/team/buddyya/feed/respository/FeedRepository.java
src/main/java/com/team/buddyya/feed/service/FeedService.java

[피드 기능 개발 #22](https://github.com/buddy-ya/be/issues/22)
- feedListRequest의 keyword를 사용하여 검색기능 추가
- feedResponse DTO에 글 작성자의 학교 추가
- commentResponse DTO에 댓글 작성자의 학교 추가
- 피드와 댓글 목데이터 추가
<br><br>
- 코드 컨벤션은 잘 지켜졌나요?
- 검색 및 getfeeds에서 필요한 예외가 있나요?
코드를 보시면 
- 검색값이 없을때(keyword가 null 혹은 blank)는 카테고리 구분하여 조회하여 반환
- 검색값이 있을때는 카테고리는 구분하지 않고 피드의 제목과 내용에서만 조회하여 피드들 반환
현재는 검색에서는 카테고리를  구분하지 않고 조회하는데
카테고리를 구분하고 싶으면 카테고리를 구분하지 않을 때 추가적인 로직이 필요합니다.
- category에 '전체'를 추가 혹은 null로 표시
- 서버에서 category가 '전체' 혹은 null일때는 카테고리를 구분하지 않고
전체 피드에서 검색하여 피드들 반환
**카테고리별로 검색하는 것을 추가하는 것이 좋을까요?**
<br><br>
<br><br>

feat: 피드 검색 기능 구현

---

src/main/java/com/team/buddyya/feed/controller/FeedController.java
src/main/java/com/team/buddyya/feed/respository/FeedRepository.java
src/main/java/com/team/buddyya/feed/service/FeedService.java

[피드 좋아요 순으로 조회[#39 ]](https://github.com/buddy-ya/be/issues/39)
<br><br>
- 좋아요 10개 이상인 피드를 최신 순으로 정렬하여 조회하는 기능
<br><br>
<br><br>
JPA의 쿼리 메서드 `findByLikeCountGreaterThanEqual(int likeCount, Pageable pageable)`를 사용하여 좋아요 10개 이상인 피드를 조회하였습니다
pageble의 getSort()를 활용하여 최신 순으로 내림차순 정렬을 하였습니다
처음에 pageable의 속성을 활용하지 않고 `findByLikeCountGreaterThanEqualOrderByCreatedDateDesc`으로 사용하려다가 쿼리 메서드가 길어졌습니다.
이번에는 pageble의 속성으로 `OrderByCreatedDateDesc`를 해결하여 쿼리 메서드를 사용하였는데 보통 2개 조건까지는 쿼리 메서드를 많이 사용하고 3개 이상부터는 @Query의 JPQL을 작성하여 해결한다고 합니다! 쿼리 메서드 길어지면 사용해봐도 좋을 것 같아요!
[JPA 쿼리 메서드 길어질 때](https://blogshine.tistory.com/389)
https://github.com/buddy-ya/be/pull/40/files
<br><br>

feat: 좋아요 10개 이상 피드 조회

---

src/main/java/com/team/buddyya/feed/dto/response/comment/CommentCreateResponse.java
src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
src/main/java/com/team/buddyya/feed/dto/response/comment/CommentUpdateResponse.java
src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
src/main/java/com/team/buddyya/student/controller/MyPageController.java
src/main/java/com/team/buddyya/student/domain/ProfileDefaultImage.java
src/main/java/com/team/buddyya/student/domain/ProfileImage.java
src/main/java/com/team/buddyya/student/domain/Student.java
src/main/java/com/team/buddyya/student/dto/response/MyPageResponse.java
src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
src/main/java/com/team/buddyya/student/repository/ProfileImageRepository.java
src/main/java/com/team/buddyya/student/service/MyPageService.java
src/main/java/com/team/buddyya/student/service/OnBoardingService.java
src/main/java/com/team/buddyya/student/service/ProfileImageService.java

[학생 프로필 추가](https://github.com/buddy-ya/be/issues/35)[#35]
<br><br>
- 학생의 프로필 이미지를 저장할 profile-image 엔티티(테이블) 추가
- 온보딩시 학생에게 기본프로필(현재6개)중에 하나 정해주는 로직 추가 
- 마이페이지에서 기본 프로필 수정 API 생성
- 댓글,피드,마이페이지의 Response DTO에 프로필 이미지 URL 추가 
<br><br>
- 코드 컨벤션은 잘 지켜졌는가?
- 빠진 예외처리는 없는가?
- 추가적으로 필요한 프로필 관련 서비스가 있을까?
- 프로필을 변경할때 프론트에서 쿼리문으로 바꾸고 싶은 기본이미지를 
키값(image1~image6)으로 넘겨줘야한다. 
-> `/mypage/update/profile-default-image?profileImageKey={imageN}`
- 추가적으로 기본 프로필이 아닌 다른 이미지를 사용하고 싶으면 추가적인 api가 필요하다.
예시) `/mypage/update/profile-image` `@ModelAttribute ProfileImageUpdateRequest `
아직 프론트/기획과 기본 프로필이 아닌 다른 이미지로 프로필 사용이 얘기되지 않아서
필요 시 api를 만들면 될 거 같다.
`ProfileImageService`에서 `updateProfileDefaultImage` 메서드를 보시면 profileImage를 `student.getProfileImage()`가 아닌
`ProfileImageRepository`에서 `student`를 이용해서 조회하고 찾지 못하면 …

feat: 학생 기본 프로필 추가

---

src/main/java/com/team/buddyya/feed/controller/FeedController.java
src/main/java/com/team/buddyya/feed/domain/Feed.java
src/main/java/com/team/buddyya/feed/respository/FeedImageRepository.java
src/main/java/com/team/buddyya/feed/service/FeedImageService.java
src/main/java/com/team/buddyya/feed/service/FeedService.java
src/main/java/com/team/buddyya/student/controller/MyPageController.java
src/main/java/com/team/buddyya/student/domain/ProfileImage.java
src/main/java/com/team/buddyya/student/repository/ProfileImageRepository.java
src/main/java/com/team/buddyya/student/service/ProfileImageService.java

[ feed 수정 시 기존 이미지 중복 업데이트 오류 수정](https://github.com/buddy-ya/be/issues/41)[#41]
[학생 프로필 추가](https://github.com/buddy-ya/be/issues/35)[#35]
-  feed 수정 시 기존 이미지 중복 업데이트 오류 수정
-  프로필 수정 POST->PATCH
-  프로필을 ProfileImageRepository로 직접 조회 -> Student.getProfileImage()로 조회
- 데이터베이스에 이미지를 저장하는 메서드와 S3에 이미지를 저장하는 메서드가 잘 구분이 되지않아
메서드명을 조금 더 명확히 해보았습니다
<br><br>
- 코드 컨벤션은 잘 지켜졌나요?
- 현재 이미지를 업데이트 하는 로직이 괜찮다고 생각하시나요?
업데이트시 해당 피드의 이미지를 모두 삭제한후 다시 새로운 이미지를 저장하는 로직으로 변경하였습니다.
원래는 Feed 엔티티 안에 있는 
```
public void uploadFeedImages(List<FeedImage> images) {
this.images= images;
}
```
를 사용해서 새로운 이미지들을 다시 저장하려고 했으나. 그렇게 하니 오류가 생겨 
FeedImageRepository를 사용해서 저장하였습니다.
추후에 왜 문제가 생기는지 알아봐야할 거 같습니다.
<br><br>
<br><br>

fix : feed 수정 시 기존 이미지 중복 업데이트 오류 수정 & 프로필 수정 POST->PATCH

---

src/main/java/com/team/buddyya/feed/dto/response/comment/CommentUpdateResponse.java

[댓글 업데이트 시 댓글에 날짜 추가[#43 ]](https://github.com/buddy-ya/be/issues/43)
<br><br>
댓글 수정 시 생성 날짜 같이 반환하도록 수정하였습니다
<br><br>
<br><br>
<br><br>

feat: 댓글 업데이트 시 생성 날짜 같이 반환

---

src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
src/main/java/com/team/buddyya/student/domain/Avatar.java
src/main/java/com/team/buddyya/student/domain/ProfileImage.java
src/main/java/com/team/buddyya/student/domain/Student.java
src/main/java/com/team/buddyya/student/domain/StudentInterest.java
src/main/java/com/team/buddyya/student/domain/StudentLanguage.java
src/main/java/com/team/buddyya/student/domain/StudentMajor.java
src/main/java/com/team/buddyya/student/repository/ProfileImageRepository.java
src/main/java/com/team/buddyya/student/service/FindStudentService.java
src/main/java/com/team/buddyya/student/service/MyPageService.java
src/main/java/com/team/buddyya/student/service/StudentService.java

[온보딩 & 핸드폰 인증 논의한점 반영](https://github.com/buddy-ya/be/issues/47)[#47 ]
<br><br>
일차적으로 논의했던 점에 대한 내용 반영
-  one to one 관계에서 fetch lazy 제거
- 양방향 관계에 편의 메소드를 추가
- 순환 참조를 방지하기 위해 findByStudentId를 별도의 서비스 FindStudentService에 분리
- 순환 참조를 방지하기 위해 findByStudentId를 제외한 나머지 서비스에서 findBy 메소드들을 제거
_(제가 담당했던 부분에서는 제거해야될 메소드는 없었습니다)_
- 매개 변수에 final 키워드 확인 후 있을 시 제거
-  모든 of를 from으로 수정
-  1 : N 관계에서 findById를 findByEntity로 수정
-  조회만 하는 메서드에 readOnly = true 추가
<br><br>
- 논의한점들이 잘 반영되어있는가?
- 코드 컨벤션에 위반 된 것들은 없는가?
- 처음 실행된 트랜잭션의 readonly 옵션은 변경되지 않는 것을 신경 쓰지 않고 일단 조회만 하는 메서드에는 readOnly=true를 명시해주었습니다.
- 양방향 관계를 단방향 관계로 바꾸었을때 Student와 같은 엔티티는 다른분들 코드가 영향이 많이받고,
@getter를 사용했어서 usage도 찾기가 어려워 일단 양방향 매핑 제외하고 수정하였습니다.
=> 단방향으로 수정하지 않되, 양방향 연관관계에서 연관관계의 주인에게 연관관계 편의 메소드를 작성한다
<br><br>
<br><br>

refactor: 온보딩과 휴대폰 인증 기능에서 논의한점 반영

---

src/main/java/com/team/buddyya/admin/service/AdminService.java
src/main/java/com/team/buddyya/auth/domain/AuthToken.java
src/main/java/com/team/buddyya/auth/service/CustomUserDetailsService.java
src/main/java/com/team/buddyya/certification/domain/StudentIdCard.java
src/main/java/com/team/buddyya/certification/service/CertificationService.java
src/main/java/com/team/buddyya/student/domain/Student.java
src/main/java/com/team/buddyya/student/service/MyPageService.java

[논의한 문제 리팩토링[#50 ]](https://github.com/buddy-ya/be/issues/50)
<br><br>
- 양방향 관계에 편의 메소드를 추가
- student 조회 서비스를 분리한 findStudentService 참조하도록 수정
- 조회 메서드에 읽기 전용 트랜잭션인 @Transactional(readOnly = true) 추가
<br><br>
- 논의한점들이 잘 반영되어있는가?
- 코드 컨벤션이 지켜졌는가?
<br><br>
읽기 전용 트랜잭션을 적용할 때 외부 api를 참조하는 경우는 어떻게 해야할까?
```
@Transactional(readOnly = true)
public CertificationResponse certificateEmail(StudentInfo studentInfo, EmailCertificationRequest emailRequest) {
Student student = findStudentService.findByStudentId(studentInfo.id());
validateStatusAndEmail(emailRequest, student);
try {
Map<String, Object> univCertResponse = UnivCert.certify(univcertApiKey, emailRequest.email(), emailRequest.univName(), true);
boolean isSuccess = (Boolean) univCertResponse.get("success");
return …
```

refactor: 논의한 문제 리팩토링

---

src/main/java/com/team/buddyya/chatting/domain/Chat.java
src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
src/main/java/com/team/buddyya/feed/domain/Bookmark.java
src/main/java/com/team/buddyya/feed/domain/Comment.java
src/main/java/com/team/buddyya/feed/domain/CommentInfo.java
src/main/java/com/team/buddyya/feed/domain/FeedImage.java
src/main/java/com/team/buddyya/feed/domain/FeedUserAction.java
src/main/java/com/team/buddyya/feed/domain/Like.java
src/main/java/com/team/buddyya/feed/respository/BookmarkRepository.java
src/main/java/com/team/buddyya/feed/respository/FeedRepository.java
src/main/java/com/team/buddyya/feed/respository/LikeRepository.java
src/main/java/com/team/buddyya/feed/service/BookmarkService.java
src/main/java/com/team/buddyya/feed/service/CategoryService.java
src/main/java/com/team/buddyya/feed/service/CommentService.java
src/main/java/com/team/buddyya/feed/service/FeedImageService.java
src/main/java/com/team/buddyya/feed/service/FeedService.java
src/main/java/com/team/buddyya/feed/service/LikeService.java
src/main/java/com/team/buddyya/student/domain/Student.java
src/main/java/com/team/buddyya/student/service/StudentService.java
src/main/resources/application-local.properties

[논의한 문제에 대해서 리팩토링 #60](https://github.com/buddy-ya/be/issues/60)
<br><br>
- 양방향 편의 메서드 작성
- 순환 참조를 피하기 위해 DB 조회시 서비스가 아닌 DAO 참조
- 컨벤션을 위해 정적 팩토리 메서드에 of 대신 from 사용
- 다대일 관계에서 조회시 findByEntity로 수정
- 서비스 계층 조회 메서드에 readOnly = true로 명시
- 테스터를 위한 `회원탈퇴 api` 삭제 api 대신 전화번호 필드에 난수 설정
<br><br>
> 정말 양방향이어야 할까요?
연관관계의 매핑을 맺을 때 가장 중요하게 생각하는 점은 `생명 주기가 동일한가?` 라고 생각해요.
`Feed`의 경우 `Like`, `Bookmark`, `Comment`, `FeedImage` 엔티티와 생명 주기가 동일할까요?
적어도 `Feed`가 삭제되었을 때 `feed_id`를 참조했던 엔티티는 모두 삭제되어야겠지만,
`Like`가 삭제되었다고 해서 `Feed`가 삭제될 필요는 없죠. (완전히 동일하지 않고, 부모가 자식을 관리하면 됩니다.)
논의한 점에 따라 양방향으로 설계했지만, 실제 자식 서비스 계층에서 `Feed`를 많이 호출하지 않는다는 점에서,
단방향으로 바꿔보려는 시도를 추후에 해보고자 합니다 :)
> 피드 관련 활동시 회원 탈퇴가 정상적으로 이뤄지지 않음
테스터를 위한 기존에 회원 탈퇴 api는 `studentRepository`에서 `student`를 삭제하는 방법이였는데요,
`Feed` 및 하위의 `Like`등이 `student`를 외래키로 참조하고 …

refactor: 논의한 문제에 대해서 리팩토링

---

src/main/java/com/team/buddyya/BuddyyaApplication.java
src/main/java/com/team/buddyya/auth/jwt/WebSocketAuthInterceptor.java
src/main/java/com/team/buddyya/chatting/controller/ChatController.java
src/main/java/com/team/buddyya/chatting/domain/Chat.java
src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
src/main/java/com/team/buddyya/chatting/domain/MessageType.java
src/main/java/com/team/buddyya/chatting/dto/request/ChatImageRequest.java
src/main/java/com/team/buddyya/chatting/dto/request/ChatMessage.java
src/main/java/com/team/buddyya/chatting/dto/request/CreateChatroomRequest.java
src/main/java/com/team/buddyya/chatting/dto/response/ChatMessageResponse.java
src/main/java/com/team/buddyya/chatting/dto/response/ChatroomResponse.java
src/main/java/com/team/buddyya/chatting/dto/response/CreateChatroomResponse.java
src/main/java/com/team/buddyya/chatting/repository/ChatRepository.java
src/main/java/com/team/buddyya/chatting/repository/ChatroomRepository.java
src/main/java/com/team/buddyya/chatting/service/ChatHandler.java
src/main/java/com/team/buddyya/chatting/service/ChatService.java
src/main/java/com/team/buddyya/common/domain/S3DirectoryName.java
src/main/java/com/team/buddyya/common/service/S3UploadService.java

[채팅방 사진 전송, 채팅방 사용되지 않는 세션 종료, 수정 사항 변경](https://github.com/buddy-ya/be/issues/76)
<br><br>
- 채팅방 사진 전송
- 채팅방 사용되지 않은 세션 주기적으로 검사 후 종료
- 채팅방 생성 조건 변경
- 채팅방 이름을 상대방 이름으로 변경
<br><br>
<br><br>
1. 처음 채팅방에 들어와 session을 저장할 때 session에 timeout을  45초로 설정합니다(PING-PONG 응답은 timeout의 1.5~2배가 적당하다고 합니다)
2. 30초 주기로 `PING ` 요청을 각 session에 보내고 프론트로부터 `PONG `응답이 오면 timeout을 45초 연장합니다 
3. PONG요청을 보내주지 않아 연장하지 못한 세션은 timeout 기간이 끝나면 세션을 닫고 메모리에서 세션을 삭제합니다.
- 소켓은 실시간성에 적합하여 이미지 같은 대용량 데이터의 경우 처리 시간이 많이 소모되어 다른 메시지가 지연이 될 수 있습니다
- 따라서 http 통신으로 이미지를 s3에 저장하고 s3에서 반환한 이미지 url을 해당 채팅방에 소켓을 통해 실시간으로 처리를 하였습니다.
+ 지금 log가 많은데 프론트와 테스트 후 지워서 재배포 하겠습니다!
<br><br>

feat: 채팅방 사진 전송, 채팅방 사용되지 않는 세션 종료, 수정 사항 변경

---

src/main/java/com/team/buddyya/notification/service/NotificationService.java

[학생 인증 알림의 data에 인증 성공 여부 추가](https://github.com/buddy-ya/be/issues/98)[#98]
<br><br>
- 학생 인증 알림의 data에 인증 성공 여부(isCertificated) 추가
<br><br>
<br><br>
<br><br>

학생 인증 알림의 data에 인증 성공 여부 추가

---

src/main/java/com/team/buddyya/chatting/controller/ChatRequestController.java
src/main/java/com/team/buddyya/chatting/dto/request/CreateChatroomRequest.java
src/main/java/com/team/buddyya/chatting/dto/response/ChatRequestResponse.java
src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
src/main/java/com/team/buddyya/feed/service/CommentService.java
src/main/java/com/team/buddyya/feed/service/FeedService.java
src/main/java/com/team/buddyya/student/repository/BlockRepository.java

- [채팅 요청 수락하기 #123](https://github.com/buddy-ya/be/issues/123)
- [피드 변경사항 반영 #55](https://github.com/buddy-ya/be/issues/55)
- **채팅 요청 목록 조회 개선:**  
기존의 채팅방 생성 API를 채팅 요청 수락하기 API로 대체하였습니다. 이는 채팅방 생성의 확장성을 고려한 변경으로, 피드 및 매칭 상황에서 각각 다른 정보를 전달할 수 있도록 분리하였습니다.
- **피드 및 댓글 조회 로직 변경:**  
피드 조회 시 차단한 유저의 피드를 제외하도록 로직을 반영하였습니다.  
또한, 부모 댓글은 조회 대상에서 제외하고, 대댓글의 경우 `isBlocked` 필드를 추가하여 클라이언트가 "차단된 유저의 댓글입니다"와 같이 렌더링할 수 있도록 설계하였습니다.
세부 작업 내용은 아래와 같습니다:
- **채팅방 생성 API 변경:**  
채팅이 필요한 경우 호출되던 기존 채팅방 생성 API를 대체하고, 피드와 매칭 등에서 별도의 API를 통해 채팅방 생성 Service 함수를 호출하도록 구현하였습니다.
- **채팅 요청 수락 처리:**  
채팅 요청을 수락하면 해당 요청이 채팅 요청 목록에서 제거되도록 하였습니다.
- **프로필 사진 반환 수정:**  
채팅 요청 목록 조회 시, 각 요청에 대해 정확한 프로필 사진이 반환되도록 개선하였습니다.
- **`BlockRepository`에서 `JPQL` 사용 이유:**  
현재 `Student`와 `Block`은 일대다 관계로, 양방향 매핑이 되어 있지 않습니다.  
A …

feat: 채팅 요청 수락하기 api 및 피드 차단 반영

---

src/main/java/com/team/buddyya/chatting/controller/ChatController.java
src/main/java/com/team/buddyya/chatting/dto/response/ChatroomListResponse.java
src/main/java/com/team/buddyya/chatting/service/ChatService.java
src/main/resources/db/migration/V2__Add_student_column_is_deleted.sql

[읽지 않은 총 메시지 개수 표시 [#131]](https://github.com/buddy-ya/be/issues/131)
<br><br>
- 읽지 않은 총 메시지 개수 표시하는 기능을 추가하였습니다
- 기존 채팅 목록을 반환하는 api에서 totalUnreadCount를 추가하였습니다
- student의 is_deleted 필드를 flyway를 통해 DB에도 반영하였습니다.
<br><br>
총 읽지 않은 메시지를 구현하기 위한 방법은 다음과 같습니다.
1. **totalUnreadCount 필드 추가 (한 번에 관리)**
2. **채팅방별 unreadCount 합산 API 사용**
1번의 경우 단일 필드로 관리가 가능하다는 장점이 있지만 채팅을 보낼 때마다, `채팅방에 들어갈 때마다 개수를 동기화` 시켜줘야 한다는 번거로움이 있습니다.
2번의 경우 이미 동기화가 되어 있는 각 채팅방의 unreadCount를 더하기만 하면 되지만, 표시할 때마다 `모든 채팅방의 unreadCount를 합산`해야 한다는 번거로움이 있습니다.
이 `두 방법 모두 비효율적`이라 생각하여 `채팅 목록을 조회할 때만 개수가 동기화`가 되도록 수정하였습니다.
기존 채팅 목록을 반환할 때 unreadCount를 가져오며, totalUnreadCount는 가져온 `채팅 목록에서 합산만 하여 별도의 쿼리 없이 읽지 않은 총 메시지를 표시해주는 방식으로 구현`하였습니다.
<br><br>
https://github.com/buddy-ya/be/pull/132/files/27e01c4ae347fc6b42c968 …

feat: 읽지 않은 총 메시지 개수 표시

---

src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
src/main/java/com/team/buddyya/student/service/OnBoardingService.java
src/main/java/com/team/buddyya/student/service/StudentService.java

[사용자 정보 동기화를 위한 DTO에 프로필사진 등록 여부 추가](https://github.com/buddy-ya/be/issues/133)[#133]
<br><br>
- 회원가입
onboardingservice
-> onboard
- 유저 정보 변경
StudentService 
-> updateUser
-> getUserInfo
-> updateUserProfileImage
- 핸드폰 인증 시 기존회원 vs 신규 회원
PhoneAuthenticationService
->checkMembership
- 코드 컨벤션에 어긋난 부분은 없나요?
- 등록되어야할 부분이 빠진 부분은 없나요?
<br><br>
<br><br>

refactor: 사용자 정보 동기화를 위한 DTO에 프로필사진 등록 여부 추가

---

src/main/java/com/team/buddyya/admin/controller/AdminController.java
src/main/java/com/team/buddyya/admin/dto/response/AdminReportResponse.java
src/main/java/com/team/buddyya/admin/dto/response/AdminReportsResponse.java
src/main/java/com/team/buddyya/admin/service/AdminService.java
src/main/java/com/team/buddyya/chatting/service/ChatService.java
src/main/java/com/team/buddyya/common/config/SecurityConfig.java
src/main/java/com/team/buddyya/feed/service/CommentService.java
src/main/java/com/team/buddyya/feed/service/FeedService.java
src/main/java/com/team/buddyya/notification/dto/response/SaveTokenResponse.java
src/main/java/com/team/buddyya/report/domain/Report.java
src/main/java/com/team/buddyya/report/domain/ReportImage.java
src/main/java/com/team/buddyya/report/dto/ReportRequest.java
src/main/java/com/team/buddyya/report/repository/ReportImageRepository.java
src/main/java/com/team/buddyya/report/service/ReportService.java
src/main/resources/db/migration/V3__Update_Report_Table.sql

[신고 시 저장 내용 수정 & 관리자 신고 조회 [#136]](https://github.com/buddy-ya/be/issues/136)
<br><br>
- 신고된 컨텐츠에 대한 내용 직접 저장하도록 수정
- 신고 목록 상세 조회
<br><br>
- 코드 컨벤션이 잘 지켜졌는가
기존에는 Feed, Comment, Chatroom에 대한 신고가 하나의 API에서 type과 신고된 ID (feedId, commentId, chatroomId)만 저장하는 방식이었습니다.
그러나 **신고된 게시글이나 댓글이 삭제되거나 수정**될 경우, **신고 내역을 조회할 때 해당 데이터(수정 시 원본 데이터)를 찾을 수 없는 문제**가 발생했습니다.
**Feed 및 Comment에 isReport, isDeleted 필드 추가**
삭제 시 신고된 경우 삭제하지 않고 isDeleted = true로 표시하여 사용자에게만 숨기기
-> 모든 게시글과 댓글에서 신고 및 삭제 상태를 검사해야 하므로 비효율적이라고 생각하였습니다
신고 시 Report 도메인에 **직접 필요한 데이터를 저장**
FeedId, CommentId를 참조하지 않고, title, content, imageUrls 등을 Report 엔티티에 직접 저장합니다.
원본 데이터가 삭제되더라도 **신고 내역이 유지되므로 신고 조회 시 데이터 유실 문제 해결**할 수 있습니다.
단, Chatroom의 경우 reportedId(chatroomId)만 저장합니다
**모든 메시지를 Report에 저장하는 것은 비효율적**이므로, chatroomId만 저장하고 신고된 채팅 메시지는 …

feat: 신고 시 저장 내용 수정 & 관리자 신고 조회

---

src/main/java/com/team/buddyya/chatting/dto/response/ChatroomDetailResponse.java
src/main/java/com/team/buddyya/chatting/dto/response/ChatroomListResponse.java
src/main/java/com/team/buddyya/chatting/dto/response/ChatroomResponse.java
src/main/java/com/team/buddyya/chatting/repository/ChatRequestRepository.java
src/main/java/com/team/buddyya/chatting/service/ChatService.java
src/main/java/com/team/buddyya/student/dto/response/UserResponse.java

[채팅방 api에 신고, 차단을 위한 buddyId 추가 [#148]](https://github.com/buddy-ya/be/issues/148)
<br><br>
- 채팅방 목록 api response에 buddyId 추가
- 채팅방 목록 api response에 `hasChatRequest`, 채팅 요청이 있는지 반환
- 알림을 통한 채팅방 정보 조회 api response에 buddyId 추가
- 상대 프로필 조회 시, 사진 있다면 사진으로, 사진 없으면 캐릭터로 반환
<br><br>
<br><br>
<br><br>

refactor: 채팅방 response에 buddyId 추가

---

src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
src/main/java/com/team/buddyya/chatting/service/ChatService.java

[채팅방 생성 시 생성 메시지 하나 증가 [#153]](https://github.com/buddy-ya/be/issues/153)
<br><br>
- 채팅방 생성 시 unreadCount +1 하도록 수정
- 읽지 않은 메시지 반환 로직 수정
<br><br>
- 코드 컨벤션에 맞게 작성되었는가?
<br><br>
<br><br>

feat: 채팅방 생성 시 생성 메시지 하나 증가 & 읽지 않은 메시지 반환 로직 수정

---

src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
src/main/java/com/team/buddyya/feed/service/CommentService.java
src/main/java/com/team/buddyya/feed/service/FeedService.java

[피드 조회, 카테고리 변경 및 댓글 차단 로직 수정 #164](https://github.com/buddy-ya/be/issues/164)
<br><br>
- 부모 댓글이 차단된 경우에도 자식 댓글이 있는 부모 댓글은 조회되도록 필터링 로직 수정
- 피드 Response에 카테고리 추가
- 나의 글, 최신순으로 조회 반환
<br><br>
<br><br>
<br><br>

fix: 피드 조회, 댓글 차단 조회 로직 변경

---

src/main/java/com/team/buddyya/feed/domain/Feed.java
src/main/java/com/team/buddyya/feed/service/CommentService.java

[자기가 쓴 글에 댓글 달 때 스스로에게 알림 오는 오류](https://github.com/buddy-ya/be/issues/166)[#166]
<br><br>
- feed 엔티티에 studentId를 주면 자신의 쓴글의 유무를 반환하는 메서드 `isMine` 추가
- `CommentService`에서 `isMine`이 아닌 즉 자신의 피드가 아닐 때만 피드의 주인에게 알림 가도록 변경
<br><br>
- 컨벤션에 어긋난 부분은 없나요?
<br><br>
<br><br>

fix: 자기가 쓴 글에 댓글 달 때 스스로에게 알림 오는 오류 수정

---

src/main/java/com/team/buddyya/feed/service/CommentService.java

[자기 피드 대댓글 알림 오류](https://github.com/buddy-ya/be/issues/168)[#168]
<br><br>
- `isFeedOwner`을 메서드 호출 최초에 조회 후 if 문에 사용
- 자기 게시물에서 대댓글을 작성했을 때 알림이 오는 오류가 발생하여,
만약 자기 게시물이 아닐 경우에만 알림을 보내는 로직으로 수정
<br><br>
- 컨벤션에 어긋난 부분은 없나요?
<br><br>
<br><br>

fix: 자기 피드 대댓글 알림 오류 수정

---

src/main/java/com/team/buddyya/admin/controller/AdminController.java
src/main/java/com/team/buddyya/admin/dto/request/BanRequest.java
src/main/java/com/team/buddyya/admin/dto/request/StudentVerificationRequest.java
src/main/java/com/team/buddyya/admin/dto/response/AdminChatMessageResponse.java
src/main/java/com/team/buddyya/admin/service/AdminService.java
src/main/java/com/team/buddyya/certification/domain/StudentIdCard.java
src/main/java/com/team/buddyya/certification/dto/response/StudentIdCardResponse.java
src/main/java/com/team/buddyya/certification/service/CertificationService.java
src/main/java/com/team/buddyya/chatting/repository/ChatRepository.java
src/main/java/com/team/buddyya/feed/exception/FeedExceptionType.java
src/main/java/com/team/buddyya/feed/service/CommentService.java
src/main/java/com/team/buddyya/feed/service/FeedService.java
src/main/java/com/team/buddyya/student/controller/UserController.java
src/main/java/com/team/buddyya/student/domain/Student.java
src/main/java/com/team/buddyya/student/dto/response/UserBanStatusResponse.java
src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
src/main/java/com/team/buddyya/student/service/StudentService.java
src/main/resources/db/migration/V5__Add_student_banned_field.sql

[관리자 제재 기능 및 학생증 승인 / 반려 수정 [#142]](https://github.com/buddy-ya/be/issues/142)
<br><br>
- 관리자 제재 기능
- UserResponse에 banned 추가
- 정지된 사용자의 정지 기간이 지나면 banned = false로 유저 정보 수정하는 기능
- 학생증 인증 반려 시 반려 사유 고지
- 게시글, 댓글 강제 삭제
신고된 목록을 확인 후 제재가 필요한 유저의 경우 유저 id와 날짜(1일, 2일, 3일)을 넘겨 `현재 시점으로부터 해당 학생의 정지일을 기록 후 isBanned = true로 변경`합니다.
isBanned = true인 학생은 서비스에 접근하지 못하며 정지가 끝나는 기간을 보여주고, 
isBanned = true일 때 `정지가 끝난 학생이면 isBanned = false로 변경하여 서비스를 이용`할 수 있도록 합니다.
학생증 승인 시 해당 학생을 DB와 S3에서 삭제하지만, `반려 시 삭제하지 않고 반려 사유를 사용자에게 보여줍니다`.
기존 피드 로직에서 유저는 자기가 작성한 피드가 아니면 삭제하지 못합니다. 하지만 `관리자는 삭제가 가능`합니다.
```
private void validateFeedOwner(StudentInfo studentInfo, Feed feed) {
if (!studentInfo.id().equals(feed.getStudent().getId()) && !studentInfo.role().equals(ADMIN)) {
throw new …
```

feat: 관리자 제재 기능 및 학생증 반려 사유 추가

---

src/main/java/com/team/buddyya/feed/domain/Comment.java
src/main/java/com/team/buddyya/feed/service/CommentService.java

[대댓글의 주인이 자신의 댓글에 대댓글을 달 때 알림 오류](https://github.com/buddy-ya/be/issues/175)[#175]
<br><br>
- 자신이 대댓글의 최상위 주인인지 확인하는 `isParent` 메서드 `Comment` 엔티티에 추가
- 대댓글 알림을 보내기전에 댓글을 작성하는 유저가 `isParent`가 아닌지 확인하여 아닐 시에만 알림을 보내는
로직으로 수정
-> 결국 대댓글 알림은 `1. 피드의 주인이 아닌 `, `2. 대댓글의 주인이 아닌 `유저가 대댓글을 작성했을 때 대댓글의 주인에게
알림이 간다
<br><br>
- 컨벤션에 어긋난 부분은 없나요?
<br><br>
<br><br>

fix: 대댓글의 주인이 자신의 댓글에 대댓글을 달 때 알림 오류 수정

---

src/main/java/com/team/buddyya/certification/service/EmailSendService.java
src/main/resources/templates/email_english.html
src/main/resources/templates/email_korean.html

[대학교 이메일 인증 외국인일 경우에 영문 이메일 전송](https://github.com/buddy-ya/be/issues/177)[#177]
<br><br>
- 자바/스프링 코드 사이에 있는 html 파일 별도의 파일로 분리
- 학생의 `isKorean` 필드를 확인 후 외국인 이면 영문 이메일 전송 한국인이면 한국어 이메일 전송 로직 구현
<br><br>
-  컨벤션에 어긋난 부분이 있나요?
- 이메일의 내용은 괜찮은가요?
<br><br>
<br><br>

refactor: 대학교 이메일 인증 외국인일 경우에 영문 이메일 전송

---

src/main/java/com/team/buddyya/common/config/SecurityConfig.java

[노드 관련 엔드포인트 security 해제](https://github.com/buddy-ya/be/issues/180)[#180]
<br><br>
- 채팅 이미지 전송 오류 해결을 위해 /node로 시작하는 엔드포인트 security 검사 안하게 설정
<br><br>
<br><br>
<br><br>

deploy: 채팅 이미지 전송 오류 해결을 위해 /node로 시작하는 엔드포인트 security 검사 안하게 설정

---

src/main/java/com/team/buddyya/notification/service/NotificationService.java

[채팅 요청 수락 알림 전송 개행 오류 수정](https://github.com/buddy-ya/be/issues/155)[#155]
<br><br>
- 채팅 요청 수락 알림 전송 개행 오류 수정
<br><br>
<br><br>
<br><br>

fix: 채팅 요청 수락 알림 전송 개행 오류 수정

---

src/main/java/com/team/buddyya/student/service/StudentService.java

[wrapper 타입 비교에서 equal 사용](https://github.com/buddy-ya/be/issues/197)[#197]
<br><br>
유저 정보 조회 시, URI로 전달된 유저 ID와 토큰에 저장된 유저 ID를 비교하는 과정에서
`== 연산자`를 사용하여 예상치 못한 결과가 발생했습니다.
이는 ID가 Long과 같은 Wrapper 클래스이기 때문에, 객체 주소를 비교하는 `== 연산자`가 아닌,
실제 값을 비교하는 `equals()`를 사용해야 합니다.
따라서, `== 연산자`를 `equals()`로 변경하여 올바르게 값을 비교하도록 수정하였습니다.
<br><br>
<br><br>
<br><br>

fix: Long은 wrapper 클래스이므로 equals로 비교하고 불필요한 로그 삭제

---

src/main/java/com/team/buddyya/student/domain/Student.java

[회원 탈퇴시 email, phonenumber를 다른 형식의 랜덤값으로 수정](https://github.com/buddy-ya/be/issues/198)[#198]
<br><br>
- 현재는 탈퇴 시 아래와 같이 임의 값으로 핸드폰 번호와 이메일 컬럼을 초기화하는데
```
this.phoneNumber = "deleted_" + UUID.randomUUID().toString().substring(0, 3);
this.email = "deleted_" + UUID.randomUUID().toString().substring(0, 4);
```
핸드폰 번호, 이메일 각각 고유한 문자열 조합은 4,096가지, 65,536가지로 탈퇴한 유저가 많아질 수록 
겹칠 확률이 매우 높으므로 UUID의 범위를 늘려 겹칠 확률을 줄이고자 합니다.
<br><br>
<br><br>
<br><br>

refactor: 탈퇴 시 핸드폰번호와 이메일을 임의값 겹칠 것을 대비하여 UUID 범위를 증가

---

src/main/java/com/team/buddyya/common/config/SecurityConfig.java

[채팅 이미지 전송 오류 수정을 위해 변경했던 사항 원상 복귀](https://github.com/buddy-ya/be/issues/187)[#187]
<br><br>
- `SecurityConfig`에서 이미지 전송 오류 수정을 위해 변경했던 node관련 설정 제거
<br><br>
<br><br>
<br><br>

refactor:  SecurityConfig에서 이미지 전송 오류 수정을 위해 변경했던 node관련 설정 제거

---

src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
src/main/java/com/team/buddyya/student/controller/UserController.java
src/main/java/com/team/buddyya/student/domain/Avatar.java
src/main/java/com/team/buddyya/student/service/StudentService.java

[로그아웃 기능](https://github.com/buddy-ya/be/issues/157)[#157]
<br><br>
- 로그 아웃 API 구현
1. 엑스포 토큰 삭제
2. `Avatar` 엔티티의 `isLoggedOut` 컬럼 true로 변경
- 재로그인 시 `Avatar` 엔티티의 `isLoggedOut` 컬럼 `false`로 변경
<br><br>
- 로그 아웃 시 ResponseDTO가 필요한가?
-  코드 컨벤션에 어긋난 부분은 없는가?
<br><br>
<br><br>

feat: 로그 아웃 기능 구현

---

src/main/java/com/team/buddyya/admin/controller/AdminController.java
src/main/java/com/team/buddyya/admin/dto/request/StudentVerificationRequest.java
src/main/java/com/team/buddyya/admin/dto/response/StudentIdCardResponse.java
src/main/java/com/team/buddyya/admin/service/AdminService.java
src/main/java/com/team/buddyya/report/exception/ReportException.java
src/main/java/com/team/buddyya/report/exception/ReportExceptionType.java
src/main/java/com/team/buddyya/report/repository/ReportRepository.java

[프론트와 논의 후 api 수정 [#191]](https://github.com/buddy-ya/be/issues/191)
<br><br>
프론트와 논의된 api에 대하여 수정합니다.
**1. 학생증 목록** 
- studentIdCards 바로 list로 반환
- 반환 목록에 학교(university) 추가
**2. 학생증 승인 반려**
- 기존에 id를 studentId로 사용하였지만 studentIdCards로 사용
- imageUrl 삭제를 위해 프론트에게 imageUrl을 받지 않고 student_id_card를 db에서 url 조회하여 s3에 삭제 요청
**3. 신고 목록 조회에서 카테고리별 분리**
- FEED, COMMENT, CHATROOM으로 분리하여 각각 조회
**4. 관리자 신고 목록 삭제 api 추가**
- 확인된 신고 목록은 남겨두지 않고 관리자가 삭제
<br><br>
<br><br>
<br><br>

feat: 프론트와 논의된 api 수정

---

src/main/java/com/team/buddyya/student/domain/Block.java
src/main/java/com/team/buddyya/student/domain/Point.java
src/main/java/com/team/buddyya/student/domain/PointStatus.java
src/main/java/com/team/buddyya/student/domain/PointType.java
src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
src/main/java/com/team/buddyya/student/repository/PointRepository.java
src/main/java/com/team/buddyya/student/repository/PointStatusRepository.java
src/main/java/com/team/buddyya/student/service/OnBoardingService.java
src/main/java/com/team/buddyya/student/service/PointService.java
src/main/java/com/team/buddyya/student/service/StudentService.java
src/main/resources/db/migration/V9__Create_point_table.sql

[포인트(티켓) 기능](https://github.com/buddy-ya/be/issues/139)[#139]
<br><br>
- Student(학생)와 1:1 매핑되는 엔티티로, 현재 보유한 포인트 총합을 관리함.
- BaseTime을 상속받아 생성 및 업데이트 시간 자동 저장.
- 최대 포인트 제한 (MAX_POINT = 100,000) 및 포인트 감소 방지 (0 미만 불가).
- Point와 N:1 매핑되는 엔티티로, 포인트 변화 이력을 저장함.
- CreatedTime을 상속받아 생성 시간 자동 저장.
- 포인트가 증가/감소하는 이유를 나타내는 열거형(Enum).
- 각 타입마다 변동되는 포인트 값(pointChange)이 설정됨
- `createPoint`: 온보딩 시 호출하여 학생의 초기 포인트를 생성하는 메서드.
초기 포인트(INITIAL)와 회원가입 포인트(SIGNUP) 상태(PointStatus)를 함께 저장.
- `updatePoint`: 특정 PointType을 기반으로 포인트를 변경.
포인트 업데이트 후 변화 이력(PointStatus)을 저장.
<br><br>
Student의 필드로 두면 포인트 관련 로직을 Student 엔티티가 직접 담당하게 되어 역할이 분리되지 않아서
Point를 **별도 엔티티로 관리하는 것이 적절하다고 판단**하였습니다.
- int를 사용하지 않은 이유 (기본 타입)
-> Point 값이 초기화되지 않거나, 특정 조건에서 null이 들어갈 수 있다면 int를 사용할 수 없기 때문
- long, Long을 사용하지 않은 이유
-> Integer의 범위인 …

feat: 포인트 기능

---

src/main/java/com/team/buddyya/match/domain/GenderType.java
src/main/java/com/team/buddyya/match/service/BasicMatchService.java

[매칭 요청시 ALL 혹은 직접 적인 성별을 받는 것으로 수정](https://github.com/buddy-ya/be/issues/209)[#209]
<br><br>
- genderType을 `ALL`, `SAME`에서 `ALL`, `MALE`, `FEMALE`로 수정
- 성별 매칭 로직(`isGenderMatch`) 수정
-> 둘다 원하는 성별이 `ALL`이면 둘의 성별에 상관없이 통과, but 둘 중에 하나라도 `ALL`이 아니면 둘의 성별이 같도록
```
private boolean isGenderMatch(GenderType matchRequestGenderType, GenderType requestedGenderType,
Gender matchRequestGender, Gender requestedGender) {
if (matchRequestGenderType == GenderType.ALL && requestedGenderType == GenderType.ALL) {
return true;
}
return matchRequestGender == requestedGender;
}
```
<br><br>
<br><br>
<br><br>

refactor: 매칭 요청시 ALL or MALE or FEMALE로 성별을 받는 것으로 수정

---

src/main/java/com/team/buddyya/point/controller/PointController.java
src/main/java/com/team/buddyya/point/domain/PointChangeType.java
src/main/java/com/team/buddyya/point/domain/PointType.java
src/main/java/com/team/buddyya/point/dto/PointListResponse.java
src/main/java/com/team/buddyya/point/dto/PointResponse.java
src/main/java/com/team/buddyya/point/repository/PointStatusRepository.java
src/main/java/com/team/buddyya/point/service/PointService.java

[유저의 포인트 기록 조회 기능](https://github.com/buddy-ya/be/issues/213)[#213]
<br><br>
- 유저의 포인트 기록 조회 기능 구현
`PointListResponse`
1. 현재 포인트 값
2. List< PointResponse >
`PointResponse`
1. id : pointStatus 아이디
2. pointType: 포인트 유형
3. pointChangeType: 포인트 변화 유형 (적립, 차감, 변화없음)
4. pointChange: 포인트 변화값
5. LocalDateTime createdDate: 포인트 변화가 일어난 시기
`응답값 예시`
```
{
"points": [
{
"id": 1,
"pointType": "signup",
"pointChangeType": "earn",
"pointChange": 100,
"createdDate": "2025-03-24T21:03:24"
},
{
"id": 14,
"pointType": "match_request",
"pointChangeType": "deduct",
"pointChange": -1,
"createdDate": "2025-03-24T21:13:08"
},
{
"id": 15,
"pointType": "cancel_match_request",
"pointChangeType": "earn",
"pointChange": 1,
"createdDate": "2025-03-24T21:13:32"
}
],
"currentPoint": 100
}
```
<br><br>
- 코드 컨벤션에 어긋난 부분이 …

feat: 유저의 포인트 기록 조회 기능 구현

---

src/main/java/com/team/buddyya/match/service/BasicMatchService.java
src/main/java/com/team/buddyya/student/service/StudentService.java

[회원 탈퇴시 매칭 요청을 삭제하고 탈퇴하거나 차단한 유저와 매칭되지 않도록 수정](https://github.com/buddy-ya/be/issues/224)[#224]
<br><br>
- 회원 탈퇴 시 유저의 매칭 요청을 삭제
- 매칭 과정에서 차단한/된 사용자와는 매칭되지 않도록 검증 추가
<br><br>
- 코드 컨벤션에 어긋난 부분은 없나요?
<br><br>
<br><br>

refactor: 회원 탈퇴 시 매칭 요청을 삭제하고 탈퇴하거나 차단한 유저와 매칭되지 않도록 수정

---

src/main/java/com/team/buddyya/certification/exception/PhoneAuthenticationExceptionType.java

[1004 에러 코드 중복](https://github.com/buddy-ya/be/issues/236)[#236]
<br><br>
- 1004 에러 코드가 중복되었으므로 SMS 인증 초과 예외를 1005번 에러코드로 수정
<br><br>
<br><br>
<br><br>

fix: 1004 에러 코드가 중복되었으므로 SMS 인증 초과 예외를 1005번 에러코드로 수정

---

src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java

[핸드폰 인증번호 검증 시 udId를 nullable하게 받도록 수정](https://github.com/buddy-ya/be/issues/241)[#241]
<br><br>
```
private void resetMessageCountIfExists(String udId) {
if (udId == null) {
return;
}
PhoneInfo phoneInfo = phoneInfoRepository.findPhoneInfoByUdId(udId)
.orElseThrow(() -> new PhoneAuthenticationException(PhoneAuthenticationExceptionType.PHONE_INFO_NOT_FOUND));
phoneInfo.resetMessageSendCount();
}
```
유저가 휴대폰 인증에 성공했다면 인증 코드 전송 횟수를 0으로 초기화 해주는데,
테스트 유저나 웹에서는 udid가 null로 들어올 수 있으므로 null일 경우에는 해당 작업을 하지 않는 것으로
로직을 수정하였습니다.
<br><br>
<br><br>
<br><br>

fix: 핸드폰 인증번호 검증 시 udId를 nullable하게 받도록 수정

---

src/main/java/com/team/buddyya/feed/dto/request/feed/FeedCreateRequest.java
src/main/java/com/team/buddyya/feed/dto/request/feed/FeedListRequest.java
src/main/java/com/team/buddyya/feed/dto/request/feed/FeedUpdateRequest.java
src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
src/main/java/com/team/buddyya/feed/repository/FeedRepository.java
src/main/java/com/team/buddyya/feed/service/FeedService.java

[피드 학교별 구분 및 카테고리화 #229](https://github.com/buddy-ya/be/issues/229)
<br><br>
- 기존 피드 목록 조회 시 사용자의 소속 대학과 전역(예: "all") 대학에 해당하는 피드만 조회하도록 변경했습니다.
- "all" 대학의 경우는 `오픈 캠퍼스`와 같이 여러 대학이 참여할 수있는 게시판이며, 현재 별도의 카테고리는 없으나 확장성을 위해 `free` 카테고리에 일단 저장할 생각입니다. (대학 스크립트 변경)
- 피드 및 댓글 작성자가 회원탈퇴 했을 경우에, DTO 필드에 두어 
클라이언트에서 탈퇴한 유저와 인터랙션을 못하게 하였습니다.
<br><br>
- 코드 컨벤션에 어긋나는 부분은 없는가?
<br><br>
<br><br>

feat: 피드 대학별 조회 반영

---

src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java

[피드 학교별 구분 및 카테고리화 #229](https://github.com/buddy-ya/be/issues/229)
<br><br>
- 대학 별 조회를 나타내는 `universityTab`을 `FeedResponse`에 필드로 두어, 프론트에서 캐싱 처리가 가능하도록 처리했습니다.
<br><br>
- 코드 컨벤션에 어긋나는 부분은 없는가?
<br><br>
<br><br>

feat: 피드 탭 정보 DTO에 제공

---

src/main/java/com/team/buddyya/point/domain/PointType.java

[feat: 기획안 기반으로 PointType별 포인트 변경값 설정](https://github.com/buddy-ya/be/issues/249)[#249]
<br><br>
- 회원가입 `+100`
- 매칭 `-35`
- 피드를 통한 채팅 요청 `-15`
- 친구초대 `+50`
<br><br>
<br><br>
<br><br>

feat: 기획안 기반으로 PointType별 포인트 변경값 설정

---

src/main/java/com/team/buddyya/admin/controller/AdminController.java
src/main/java/com/team/buddyya/admin/service/AdminService.java
src/main/java/com/team/buddyya/point/domain/PointType.java
src/main/java/com/team/buddyya/report/domain/ReportType.java
src/main/java/com/team/buddyya/student/domain/CharacterProfileImage.java

[응답 없는 매칭 사용자를 관리자에게 신고하고 포인트 환급 기능 [#254]](https://github.com/buddy-ya/be/issues/254)
<br><br>
- 신고 type에 CHATROOM_NO_RESPONSE 추가
- PointType에 `CHATROOM_NO_RESPONSE_REFUND("chatroom_no_response_refund", 35, PointChangeType.EARN);` 추가
- roomId와 reportUserId를 통해 관리자가 해당 사용자에게 포인트를 환급하는 기능 추가
- 캐릭터 프로필 9번 삭제
<br><br>
- 컨벤션이 잘 지켜졌는가?
- point 정책에 맞게 설계되어 있는가?
<br><br>
<br><br>

feat: 응답 없는 매칭 사용자를 관리자에게 신고하고 포인트 환급 기능

---

src/main/java/com/team/buddyya/notification/service/NotificationService.java
src/main/java/com/team/buddyya/student/service/InvitationService.java

[추천인 코드 이벤트 참여 시 추천인에게 포인트 지급 알림 기능 추가](https://github.com/buddy-ya/be/issues/260)[#260]
<br><br>
- 추천인 코드 이벤트 참여 시 추천인에게 포인트 지급 알림 기능 추가
<br><br>
- 알림 제목과 본문이 적절한가?
```
private static final String INVITATION_REWARD_TITLE_KR = "포인트가 지급되었어요!";
private static final String INVITATION_REWARD_TITLE_EN = "You have received points!";
private static final String INVITATION_REWARD_BODY_KR = "추천 이벤트 참여로 포인트가 적립되었어요.";
private static final String INVITATION_REWARD_BODY_EN = "You received points from a referral event.";
```
<br><br>
<br><br>

feat: 추천인 코드 이벤트 참여 시 추천인에게 포인트 지급 알림 기능 추가

---

src/main/java/com/team/buddyya/chatting/service/ChatRequestService.java
src/main/java/com/team/buddyya/point/domain/PointType.java

[매칭 요청을 거절하거나 24시간이 지났을 경우 포인트 환급](https://github.com/buddy-ya/be/issues/259)[#269]
<br><br>
- 매칭 요청을 거절하면 포인트 환급
- 매칭 요청을 한지 24시간이 지났을 때 상대방이 승인하지 않으면 포인트 환급
<br><br>
<br><br>
<br><br>

feat: 매칭 요청을 거절하거나 24시간이 지났을 경우 포인트 환급 로직 추가

---

src/main/java/com/team/buddyya/certification/service/MessageSendService.java

[문자 인증 코드 전송은 영문으로 수정](https://github.com/buddy-ya/be/issues/274)[#274]
<br><br>
- 문자 인증 코드 전송은 영문으로 수정
<br><br>
- 영문 문자 메시지가 자연스러운가요?
`private static final String MESSAGE_TEXT_FORMAT = "[Buddyya] Enter the code [%s] on the screen to confirm it's you!";`
<br><br>
<br><br>

refactor: 문자 인증 코드 전송은 영문으로 수정

---

src/main/java/com/team/buddyya/admin/service/AdminService.java
src/main/java/com/team/buddyya/feed/service/CommentService.java
src/main/java/com/team/buddyya/match/service/BasicMatchService.java
src/main/java/com/team/buddyya/notification/service/NotificationService.java

[대댓글 알림 오류 수정 및 응답 없음 포인트 환급 알림 추가](https://github.com/buddy-ya/be/issues/283)[#283]
<br><br>
- 대댓글 알림 오류 수정
`대댓글 작성 시`
1. 댓글 작성자가 `피드의 주인`이면 알림 전송 가면 안됨
-> 피드의 주인 스스로에게 대댓글 알림 가는 것을 방지
2. 댓글 작성자가 `댓글의 주인`이면 알림 전송 가면 안됨
-> 댓글의 주인 스스로에게 대댓글 알림 가는 것을 방지
3. **`댓글의 주인`이 `피드의 주인`이면 알림 전송 가면 안됨 ( 처리 안되어었던 로직 )**
-> 피드의 주인에게 `일반 댓글 알림` + `대댓글 알림` 한번에 두개의 알림이 가는 것을 방지
- 응답 없음 포인트 환급 알림 추가
- 매칭 성공 시 로그 추가
<br><br>
<br><br>
<br><br>

대댓글 알림 오류 수정 및 응답 없음 포인트 환급 알림 추가

---

src/main/java/com/team/buddyya/certification/domain/RegisteredPhone.java
src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
src/main/java/com/team/buddyya/notification/service/NotificationService.java
src/main/java/com/team/buddyya/point/domain/PointType.java
src/main/java/com/team/buddyya/student/service/StudentService.java
src/main/resources/db/migration/V22__Add_last_attendance_date_registred_phone_info.sql

[출석 이벤트 포인트 지급 기능](https://github.com/buddy-ya/be/issues/303)[#303]
<br><br>
- 유저가 하루에 한번 앱에 접속하면 15포인트를 지급한다.
- 유저가 하루에 마지막으로 접속한 날짜를 기록하는 컬럼 추가 (`lastAttendanceDate`)
- 출석 이벤트 포인트 지급 기능 구현
`접속시 동작 흐름`
1. 사용자가 앱 접속하여 나의 정보 조회(getUserInfo 호출)
2. `RegisteredPhone`에서 해당 유저의 `lastAttendanceDate` 조회
3. 오늘 날짜와 비교:
- 같으면: 아무 일도 하지 않음 (이미 출석 완료)
- 다르면 or 방금 회원가입하여서 null값일 때:
1. lastAttendanceDate = 오늘 날짜로 업데이트
2. 포인트 지급
3. 알림 메시지 전송
- 친구 초대 이벤트 추가 포인트 `+50` -> `+100`으로 증가
<br><br>
- 코드 컨벤션에 어긋난 부분은 없나요?
- 알림 내용은 적당한 가요?
```
private static final String ATTENDANCE_REWARD_TITLE_KR = "출석 완료!";
private static final String ATTENDANCE_REWARD_TITLE_EN = "Checked In!";
private static final String ATTENDANCE_REWARD_BODY_KR = "매일 출석하면 포인트가 쌓여요. 오늘도 +15포인트 적립!";
private static final String …
```

feat: 출석 이벤트 포인트 지급 기능 구현

---

src/main/java/com/team/buddyya/admin/service/AdminService.java
src/main/java/com/team/buddyya/match/service/BasicMatchService.java
src/main/java/com/team/buddyya/notification/domain/RequestNotification.java
src/main/java/com/team/buddyya/notification/service/NotificationService.java
src/main/java/com/team/buddyya/student/service/InvitationService.java
src/main/java/com/team/buddyya/student/service/StudentService.java

[매칭 알림 본문 개선 및 포인트 변화 시 현재 포인트 포함](https://github.com/buddy-ya/be/issues/307)[#307]
<br><br>
- 매칭 알림 본문 개선
- 포인트 변화 시 현재 포인트 포함
<br><br>
- 즉시 매칭된 유저에게 알림을 전송해야될까?
<br><br>
<br><br>

refactor: 매칭 알림 본문 개선 및 포인트 변화 시 현재 포인트 포함

---

src/main/java/com/team/buddyya/chatting/controller/ChatRequestController.java
src/main/java/com/team/buddyya/chatting/exception/ChatExceptionType.java
src/main/java/com/team/buddyya/chatting/repository/ChatroomRepository.java
src/main/java/com/team/buddyya/chatting/service/ChatRequestService.java
src/main/java/com/team/buddyya/feed/domain/Bookmark.java
src/main/java/com/team/buddyya/feed/domain/Feed.java
src/main/java/com/team/buddyya/feed/domain/FeedLike.java
src/main/java/com/team/buddyya/feed/dto/request/feed/FeedCreateRequest.java
src/main/java/com/team/buddyya/feed/dto/request/feed/FeedUpdateRequest.java
src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
src/main/java/com/team/buddyya/feed/repository/BookmarkRepository.java
src/main/java/com/team/buddyya/feed/service/BookmarkService.java
src/main/java/com/team/buddyya/feed/service/FeedLikeService.java
src/main/java/com/team/buddyya/feed/service/FeedService.java
src/main/resources/db/migration/V23__Add_is_profile_visible_to_feed.sql
src/main/resources/db/migration/V24__Update_bookmark_unique_feed_student.sql
src/main/resources/db/migration/V25__Update_feedLike_unique_feed_student.sql

[피드에서 채팅 요청 시 로직 개선 #305](https://github.com/buddy-ya/be/issues/305)
- **채팅 요청 생성 로직 변경**  
- 차단 관계가 존재하거나, 두 사용자 간의 가장 최근 채팅방이 active 상태(둘 다 채팅방에 남아 있는 상태)인 경우에만 채팅 요청 생성이 불가하도록 개선했습니다.
- **북마크 중복 저장 방지**  
- 동일 학생-피드 조합의 북마크가 여러 건 저장되지 않도록 DB 테이블에 (feed_id, student_id) 복합 유니크 제약 조건을 추가하고자 하였으나, 기존에 엔티티에 제약 조건을 건 사례가 없어 서비스 로직에서 이를 개선하고자 하였습니다. (논의가 필요합니다.)
- 서비스 로직에서 북마크 토글 시 피드-학생 조건에 해당하는 모든 북마크를 조회하여 삭제 후 처리하도록 개선했습니다.
- **피드 생성 시 프로필 공개 여부 포함**  
- 피드 생성 시 사용자가 프로필을 공개할지 여부(예: `is_profile_visible`)를 설정할 수 있도록 엔티티 및 마이그레이션 스크립트를 추가했습니다.
- **채팅 요청 생성 로직**  
- 현재 차단 관계 및 최근 채팅방의 active 상태 검사에 대해 추가로 고려할 사항은 없는지 검토해 주세요.
- **북마크 중복 저장 문제**  
- 북마크를 빠르게 연타할 경우 중복 저장되는 현상을 DB의 UNIQUE 제약 조건으로 해결하는 방법을 적용해도 될지 알려주세요. 혹은 서비스 로직만으로 괜찮을까요?
- **피드 생성 시 프로필 공개 여부**  
- 프로필 공개 여부 필드의 …

Refactor: 채팅 요청 생성 로직 변경 및 피드 생성시 프로필 공개 여부 포함 

---

src/main/java/com/team/buddyya/student/dto/response/UserResponse.java

[상대 프로필 조회시 인증 여부 반환](https://github.com/buddy-ya/be/issues/328)
<br><br>
- 상대 프로필 조회(`getUserInfo` -> fromOtherUserInfo) 에 isCertificated 값 추가해서 반환
<br><br>
<br><br>
<br><br>

refactor: 상대방 프로필 조회시 인증 여부 추가

---

src/main/java/com/team/buddyya/admin/dto/response/StudentVerificationResponse.java
src/main/java/com/team/buddyya/admin/service/AdminService.java
src/main/java/com/team/buddyya/certification/controller/CertificationController.java
src/main/java/com/team/buddyya/certification/domain/RegisteredPhone.java
src/main/java/com/team/buddyya/certification/dto/response/CertificationResponse.java
src/main/java/com/team/buddyya/certification/service/CertificationService.java
src/main/java/com/team/buddyya/mission/controller/MissionController.java
src/main/java/com/team/buddyya/mission/dto/PointMissionResponse.java
src/main/java/com/team/buddyya/mission/dto/PointMissionRewardResponse.java
src/main/java/com/team/buddyya/mission/service/MissionService.java
src/main/java/com/team/buddyya/notification/service/NotificationService.java
src/main/java/com/team/buddyya/point/controller/PointController.java
src/main/java/com/team/buddyya/point/domain/PointType.java
src/main/java/com/team/buddyya/point/dto/PointMissionResponse.java
src/main/java/com/team/buddyya/point/service/PointService.java
src/main/resources/db/migration/V27__Add_registered_phone_number_has_certificated.sql

[기존 회원가입 포인트 정책 개선 및 인증 미션 도입](https://github.com/buddy-ya/be/issues/327)[#327]
<br><br>
- 기존 회원 가입 포인트 100에서 50에 인하
- 인증시 100 포인트 지급
1. 이메일 인증
2. 학생증 인증
- 미션 페이지에 인증 여부 응답값에 추가
<br><br>
- 포인트가 변동될 수도 있고 변동되지 않을 수도 있는 상황에서, 응답 DTO에는 변동 여부와 관계없이 항상 현재 포인트 정보를 포함해야 합니다. 현재는 인증 처리 이후 포인트를 조회하여 응답에 사용하고 있는데, 이보다 더 적절한 DTO 구조가 있다면 제안 부탁드립니다.
<br><br>
<br><br>

기존 회원가입 포인트 정책 개선 및 인증 미션 도입

---

src/main/java/com/team/buddyya/point/domain/PointType.java
src/main/java/com/team/buddyya/point/service/PointService.java

[회원가입 포인트 정책 변경에 따른 ENUM 분리](https://github.com/buddy-ya/be/issues/335)[#335]
<br><br>
기존 회원가입 포인트는 100이었으나, 최근 정책 변경으로 새로운 가입자에게 지급되는 포인트가 달라졌습니다.
하지만 기존 ENUM을 그대로 사용할 경우 과거 가입자에게도 잘못된 포인트가 계산되어 총 포인트가 잘못 표시되는 문제가 있었습니다.
이에 따라 과거 정책의 포인트 값을 유지하기 위해 기존 ENUM은 그대로 두고,
신규 정책을 반영한 새로운 회원가입 포인트 ENUM을 추가하였습니다.
총 포인트 계산 로직도 이에 맞게 수정하였습니다.
<br><br>
<br><br>
<br><br>

refactor: 회원가입 포인트 정책 변경에 따른 NEW_SIGNUP 분리

---

src/main/java/com/team/buddyya/point/domain/PointType.java
src/main/java/com/team/buddyya/point/service/PointService.java

[축제 기간 동안 회원 가입시 추가 포인트 지급](https://github.com/buddy-ya/be/issues/340)[#340]
<br><br>
- 회원 가입 시 FESTIVAL_REWARD 포인트를 추가로 지급하는 로직을 적용했습니다.
- 탈퇴 이력이 없는 회원에게만 지급되며, 페스티벌 종료 시 해당 로직은 주석 처리 또는 제거 예정입니다.
<br><br>
<br><br>
<br><br>

feat: 페스티벌 기간동안 회원 가입 시에 추가적인 리워드 지급

---

src/main/java/com/team/buddyya/feed/controller/FeedController.java
src/main/java/com/team/buddyya/feed/domain/Feed.java
src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
src/main/java/com/team/buddyya/feed/exception/FeedExceptionType.java
src/main/java/com/team/buddyya/feed/service/FeedService.java
src/main/java/com/team/buddyya/student/domain/Role.java
src/main/java/com/team/buddyya/student/domain/University.java
src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
src/main/resources/db/migration/V28__Add_feed_pinned.sql
src/main/resources/db/migration/V29__Add_university_match_and_feed_active.sql
src/main/resources/db/migration/V30__Update_university_column.sql
src/test/java/com/team/buddyya/student/controller/UserControllerTest.java

[인기 카테고리 구현 및 수도권 대학 확장 #347](https://github.com/buddy-ya/be/issues/347)
<br><br>
- `university` 테이블에 `matchActive`(기본값: true), `feedActive`(기본값: false) 컬럼 추가
- 인기 게시판 조회 API 및 정렬 로직 구현
- 피드 고정글(`pinned`) 기능 구현 및 정렬 적용
- 피드·댓글 조회 시 `Role = OWNER` 일 경우 버디야 프로필 이미지 반환 로직 추가 (버디야 공식 공지용)
- 피드·댓글 응답에 인증 여부(`isCertificated`) 필드 포함
<br><br>
<br><br>
<br><br>

feat: 피드 인기, 고정게시글 기능 구현 

---

src/main/java/com/team/buddyya/feed/service/FeedService.java

[인기 카테고리 구현 및 수도권 확장 #347](https://github.com/buddy-ya/be/issues/347) 
<br><br>
컨트롤러가 아닌 서비스 레이어에서 피드 목록을 정렬하고 있는 것을 확인했고,
`createdDate`보다 `pinned`에 우선순위를 두어 정렬시켰습니다.
<br><br>
<br><br>
<br><br>

fix: 'pinned' 서비스에서 정렬 막힌 현상 해결 (#347)

---

src/main/java/com/team/buddyya/event/controller/EventController.java
src/main/java/com/team/buddyya/event/domain/Coupon.java
src/main/java/com/team/buddyya/event/dto/CouponRequest.java
src/main/java/com/team/buddyya/event/dto/CouponResponse.java
src/main/java/com/team/buddyya/event/exception/EventException.java
src/main/java/com/team/buddyya/event/exception/EventExceptionType.java
src/main/java/com/team/buddyya/event/repository/CouponRepository.java
src/main/java/com/team/buddyya/event/service/EventService.java
src/main/java/com/team/buddyya/point/domain/PointType.java
src/main/resources/db/migration/V31__Create_coupon_table.sql

[버디야 부스 쿠폰 등록 이벤트 구현](https://github.com/buddy-ya/be/issues/355)[#355]
<br><br>
- `Coupon` 엔티티 생성
- `Coupon` 코드 입력 시 쿠폰의 유효성과 사용 여부를 검사
1. 등록되지 않은 쿠폰 코드일 경우 예외 반환
2. 이미 사용된 쿠폰 코드일 경우 예외 반환
- 유효한 쿠폰일 경우 포인트 업데이트 후 업데이트된 포인트와 포인트 변화 반환
<br><br>
<br><br>
<br><br>

feat: 쿠폰 등록 이벤트 기능 구현

---

src/main/java/com/team/buddyya/notification/controller/NotificationController.java
src/main/java/com/team/buddyya/notification/dto/request/PushToAllUsersRequest.java
src/main/java/com/team/buddyya/notification/service/NotificationService.java

[유저 전체에게 알림이 가는 기능 구현](https://github.com/buddy-ya/be/issues/358)[#358]
<br><br>
- 포스트맨으로 유저 전체에게 중요 알림을 보내는 API 구현
- 알림 내용
```
{
"to": "ExponentPushToken[xxxxxxx]",
"title": "Important notification from Buddyya",
"body": "이번 주말 행사 안내 📢",
"data": {
"feedId": 42,
"type": "FEED"
}
}
```
<br><br>
- 해당 기능이 ADMIN 유저의 여부를 확인할 필요가 있을까요?
<br><br>
<br><br>

feat: 유저 전체에게 알림이 가는 기능 구현

---

src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
src/main/java/com/team/buddyya/student/dto/response/UserResponse.java

[로그인시 매칭 프로필 전달 안되는 이슈 #362](https://github.com/buddy-ya/be/issues/362)
<br><br>
- `UserResponse` `checkMemberShip`에서 기존회원일 경우 매칭프로필을 포함해서 반환
<br><br>
<br><br>
<br><br>

fix: 로그인시 기존 유저일 경우 매칭 프로필 전달
